'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure
Imports CARS.CONFIG_NOTIFI
Namespace CARSConfigEntities

Partial Public Class CARSEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=CARSEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property TBL_CONFIG_NOTIFICATION() As DbSet(Of TBL_CONFIG_NOTIFICATION)

End Class
End Namespace
