'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Namespace CONFIG_NOTIFI
Partial Public Class TBL_CONFIG_NOTIFICATION
    Public Property IdNotification As Integer
    Public Property NotificationMessage As String
    Public Property NotificationType As Integer
    Public Property IsNotification As Boolean
    Public Property WO_NO As String
    Public Property WO_PREFIX As String
    Public Property WO_JOB_NO As Nullable(Of Integer)
    Public Property CreatedBy As String
    Public Property ModifiedBy As String
    Public Property ModifiedDate As Nullable(Of Date)
    Public Property CreatedDate As Date

End Class
End Namespace
