IF EXISTS(
	SELECT 
    OBJECT_NAME(OBJECT_ID) AS NameofConstraint
        ,SCHEMA_NAME(schema_id) AS SchemaName
        ,OBJECT_NAME(parent_object_id) AS TableName
        ,type_desc AS ConstraintType
    FROM sys.objects
    WHERE type_desc LIKE '%CONSTRAINT'
        AND OBJECT_NAME(OBJECT_ID)='FK_CONTACT_PERSON_FUNCTION')
	BEGIN
		ALTER TABLE dbo.TBL_MAS_CUSTOMER_CONTACT_PERSON 
		DROP CONSTRAINT FK_CONTACT_PERSON_FUNCTION
	END
IF EXISTS(
	SELECT 
    OBJECT_NAME(OBJECT_ID) AS NameofConstraint
        ,SCHEMA_NAME(schema_id) AS SchemaName
        ,OBJECT_NAME(parent_object_id) AS TableName
        ,type_desc AS ConstraintType
    FROM sys.objects
    WHERE type_desc LIKE '%CONSTRAINT'
        AND OBJECT_NAME(OBJECT_ID)='FK_CONTACT_PERSON_TITLE')
	BEGIN
		ALTER TABLE dbo.TBL_MAS_CUSTOMER_CONTACT_PERSON 
		DROP CONSTRAINT FK_CONTACT_PERSON_TITLE
	END

IF NOT EXISTS(
    SELECT *
    FROM sys.columns 
    WHERE Name      = N'CP_TITLE_CODE'
      AND Object_ID = Object_ID(N'TBL_MAS_CUSTOMER_CONTACT_PERSON'))
BEGIN
    ALTER TABLE dbo.TBL_MAS_CUSTOMER_CONTACT_PERSON
	ADD CP_TITLE_CODE VARCHAR(10)
END
IF NOT EXISTS(
    SELECT *
    FROM sys.columns 
    WHERE Name      = N'CP_FUNCTION_CODE'
      AND Object_ID = Object_ID(N'TBL_MAS_CUSTOMER_CONTACT_PERSON'))
BEGIN
    ALTER TABLE dbo.TBL_MAS_CUSTOMER_CONTACT_PERSON
	ADD CP_FUNCTION_CODE VARCHAR(10)
END

IF EXISTS(
	SELECT 
		OBJECT_NAME(OBJECT_ID) AS NameofConstraint
			,SCHEMA_NAME(schema_id) AS SchemaName
			,OBJECT_NAME(parent_object_id) AS TableName
			,type_desc AS ConstraintType
		FROM sys.objects
		WHERE type_desc LIKE '%CONSTRAINT'
        AND OBJECT_NAME(OBJECT_ID)='TITLE_CODE')
	BEGIN
		ALTER TABLE dbo.TBL_MAS_CUSTOMER_CONTACT_PERSON_TITLE 
		DROP CONSTRAINT TITLE_CODE
	END
ALTER TABLE dbo.TBL_MAS_CUSTOMER_CONTACT_PERSON_TITLE 
ADD CONSTRAINT TITLE_CODE UNIQUE (TITLE_CODE)
ALTER TABLE dbo.TBL_MAS_CUSTOMER_CONTACT_PERSON_TITLE 
ALTER COLUMN TITLE_CODE VARCHAR(10) NOT NULL

IF EXISTS(
	SELECT 
    OBJECT_NAME(OBJECT_ID) AS NameofConstraint
        ,SCHEMA_NAME(schema_id) AS SchemaName
        ,OBJECT_NAME(parent_object_id) AS TableName
        ,type_desc AS ConstraintType
    FROM sys.objects
    WHERE type_desc LIKE '%CONSTRAINT'
        AND OBJECT_NAME(OBJECT_ID)='FUNCTION_CODE')
	BEGIN
		ALTER TABLE dbo.TBL_MAS_CUSTOMER_CONTACT_PERSON_FUNCTION 
		DROP CONSTRAINT FUNCTION_CODE
	END
ALTER TABLE dbo.TBL_MAS_CUSTOMER_CONTACT_PERSON_FUNCTION
ADD CONSTRAINT FUNCTION_CODE UNIQUE (FUNCTION_CODE)
ALTER TABLE dbo.TBL_MAS_CUSTOMER_CONTACT_PERSON_FUNCTION
ALTER COLUMN FUNCTION_CODE VARCHAR(10) NOT NULL


ALTER TABLE dbo.TBL_MAS_CUSTOMER_CONTACT_PERSON ADD CONSTRAINT
	FK_CONTACT_PERSON_FUNCTION FOREIGN KEY
	(
	CP_FUNCTION_CODE
	) REFERENCES dbo.TBL_MAS_CUSTOMER_CONTACT_PERSON_FUNCTION
	(
	FUNCTION_CODE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 


ALTER TABLE dbo.TBL_MAS_CUSTOMER_CONTACT_PERSON ADD CONSTRAINT
	FK_CONTACT_PERSON_TITLE FOREIGN KEY
	(
	CP_TITLE_CODE
	) REFERENCES dbo.TBL_MAS_CUSTOMER_CONTACT_PERSON_TITLE
	(
	TITLE_CODE
	) ON UPDATE  CASCADE 
	 ON DELETE  CASCADE 

IF EXISTS(
    SELECT *
    FROM sys.columns 
    WHERE Name      = N'CP_ID_TITLE'
      AND Object_ID = Object_ID(N'TBL_MAS_CUSTOMER_CONTACT_PERSON'))
BEGIN
    ALTER TABLE dbo.TBL_MAS_CUSTOMER_CONTACT_PERSON
	DROP COLUMN CP_ID_TITLE
END
IF EXISTS(
    SELECT *
    FROM sys.columns 
    WHERE Name      = N'CP_ID_FUNCTION'
      AND Object_ID = Object_ID(N'TBL_MAS_CUSTOMER_CONTACT_PERSON'))
BEGIN
    ALTER TABLE dbo.TBL_MAS_CUSTOMER_CONTACT_PERSON
	DROP COLUMN CP_ID_FUNCTION
END