

IF NOT EXISTS(SELECT * FROM syscolumns WHERE id=object_id('TBL_MAS_USERS') AND name='FLG_RESOURCE')
BEGIN
	ALTER TABLE TBL_MAS_USERS
	ADD FLG_RESOURCE Bit DEFAULT NULL
END

IF NOT EXISTS(SELECT * FROM syscolumns WHERE id=object_id('TBL_MAS_USERS') AND name='RESOURCE_NAME')
BEGIN
	ALTER TABLE TBL_MAS_USERS
	ADD RESOURCE_NAME Varchar(20) DEFAULT NULL
END

