ALTER TABLE TBL_WO_HEADER ADD FLG_VEH_PKK bit
ALTER TABLE TBL_WO_HEADER ADD FLG_VEH_PKK_AFTER bit
ALTER TABLE TBL_WO_HEADER ADD FLG_VEH_PER_SERVICE bit
ALTER TABLE TBL_WO_HEADER ADD FLG_VEH_RENTAL_CAR bit
ALTER TABLE TBL_WO_HEADER ADD FLG_VEH_MOIST_CTRL bit
ALTER TABLE TBL_WO_HEADER ADD FLG_VEH_TECTYL bit