ALTER TABLE TBL_MAS_VEHICLE ADD  DT_VEH_PKK datetime
ALTER TABLE TBL_MAS_VEHICLE ADD  DT_VEH_PKK_AFTER datetime
ALTER TABLE TBL_MAS_VEHICLE ADD  DT_VEH_PER_SERVICE datetime
ALTER TABLE TBL_MAS_VEHICLE ADD  DT_VEH_RENTAL_CAR datetime
ALTER TABLE TBL_MAS_VEHICLE ADD  DT_VEH_MOIST_CTRL datetime
ALTER TABLE TBL_MAS_VEHICLE ADD  DT_VEH_TECTYL datetime