IF NOT EXISTS(SELECT * FROM syscolumns WHERE id=object_id('TBL_TR_JOB_ACTUAL_HISTORY') AND name='TOTAL_CLOCKED_TIME')
BEGIN 
ALTER TABLE TBL_TR_JOB_ACTUAL_HISTORY
ADD TOTAL_CLOCKED_TIME VARCHAR(20)
END