IF NOT EXISTS(SELECT * FROM syscolumns WHERE id=object_id('TBL_WO_DEBITOR_DETAIL') AND name='CUST_DISC_GENERAL')
BEGIN 
	ALTER TABLE TBL_WO_DEBITOR_DETAIL ADD CUST_DISC_GENERAL INTEGER 
END


IF NOT EXISTS(SELECT * FROM syscolumns WHERE id=object_id('TBL_WO_DEBITOR_DETAIL') AND name='CUST_DISC_LABOUR')
BEGIN 
	ALTER TABLE TBL_WO_DEBITOR_DETAIL ADD CUST_DISC_LABOUR INTEGER 
END


IF NOT EXISTS(SELECT * FROM syscolumns WHERE id=object_id('TBL_WO_DEBITOR_DETAIL') AND name='CUST_DISC_SPARES')
BEGIN 
	ALTER TABLE TBL_WO_DEBITOR_DETAIL ADD CUST_DISC_SPARES INTEGER 
END

IF NOT EXISTS(SELECT * FROM syscolumns WHERE id=object_id('TBL_WO_JOB_DETAIL') AND name='SPARE_DISCOUNT')
BEGIN 
	ALTER TABLE TBL_WO_JOB_DETAIL ADD SPARE_DISCOUNT INTEGER 
END