IF NOT EXISTS(SELECT * FROM syscolumns WHERE id=object_id('TBL_WO_DEBTOR_INVOICE_DATA') AND name='DISC_PERCENT')
BEGIN 
ALTER TABLE TBL_WO_DEBTOR_INVOICE_DATA
ADD DISC_PERCENT DECIMAL(13,2)
END

IF NOT EXISTS(SELECT * FROM syscolumns WHERE id=object_id('TBL_WO_DEBTOR_INVOICE_DATA') AND name='DEL_QTY')
BEGIN 
ALTER TABLE TBL_WO_DEBTOR_INVOICE_DATA
ADD DEL_QTY DECIMAL(15,2)
END

