ALTER TABLE TBL_SPR_IMPORTPRICEFILE ADD NO_CRT_UPD_SP_REG bit  
ALTER TABLE TBL_SPR_IMPORTPRICEFILE ADD DLT_AND_ADD_SP_REG bit 
ALTER TABLE TBL_SPR_IMPORTPRICEFILE ADD UPDATE_SP_REG bit  
ALTER TABLE TBL_SPR_IMPORTPRICEFILE ADD UPDATE_LOCAL_SP bit  
ALTER TABLE TBL_SPR_IMPORTPRICEFILE ADD UPDATE_SP_ON_JOB_PKG bit  