USE [CARSDEV]
GO

/****** Object:  Table [dbo].[TBL_MAS_CURRENCY]    Script Date: 15.02.2017 15.08.03 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TBL_MAS_CURRENCY](
	[ID_CURRENCY] [int] IDENTITY(1,1) NOT NULL,
	[CURRENCY_CODE] [varchar](10) NOT NULL,
	[CURRENCY_DESCRIPTION] [varchar](100) NOT NULL,
	[CURRENCY_RATE] [decimal](18, 2) NULL,
	[CURRENCY_UNIT] [int] NULL
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


