GO
/*ERROR MESSAGES*/

DELETE FROM TBL_MAS_ERR_MESSAGE WHERE ERR_ID = 'D_CREORDER'

INSERT INTO TBL_MAS_ERR_MESSAGE(ERR_ID, ERR_DESC, ID_LANG,REMARK,ISDATA,[TYPE], CREATED_BY, DT_CREATED) 
VALUES('D_CREORDER','CreditNote',1,'',1,0,'ADMIN', GETDATE())     

INSERT INTO TBL_MAS_ERR_MESSAGE(ERR_ID, ERR_DESC, ID_LANG,REMARK,ISDATA, [TYPE], CREATED_BY, DT_CREATED) 
VALUES('D_CREORDER','KreditNota',3,'',1,0,'ADMIN', GETDATE())     

INSERT INTO TBL_MAS_ERR_MESSAGE(ERR_ID, ERR_DESC, ID_LANG,REMARK,ISDATA, [TYPE], CREATED_BY, DT_CREATED) 
VALUES('D_CREORDER','CreditNote_G',2,'',1,0,'ADMIN', GETDATE())

GO
