USE [CARSDEV]
GO

/****** Object:  Table [dbo].[TBL_MAS_CUSTOMER_ACTIVITY]    Script Date: 12.06.2019 15:18:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TBL_MAS_CUSTOMER_ACTIVITY](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[CUSTOMER_ID] [varchar](10) NOT NULL,
	[ACTIVITY_NAME] [nchar](150) NULL,
	[TYPE] [nchar](100) NOT NULL,
	[DATE] [datetime] NOT NULL,
	[SIGNATURE] [nchar](100) NULL,
 CONSTRAINT [PK_TBL_MAS_CUSTOMER_ACTIVITY] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TBL_MAS_CUSTOMER_ACTIVITY]  WITH CHECK ADD  CONSTRAINT [FK_TBL_MAS_CUSTOMER_ACTIVITY_TBL_MAS_CUSTOMER] FOREIGN KEY([CUSTOMER_ID])
REFERENCES [dbo].[TBL_MAS_CUSTOMER] ([ID_CUSTOMER])
GO

ALTER TABLE [dbo].[TBL_MAS_CUSTOMER_ACTIVITY] CHECK CONSTRAINT [FK_TBL_MAS_CUSTOMER_ACTIVITY_TBL_MAS_CUSTOMER]
GO

