
GO
/*ERROR MESSAGES*/

DELETE FROM TBL_MAS_ERR_MESSAGE WHERE ERR_ID = 'MECHCLKINEXIST'

INSERT INTO TBL_MAS_ERR_MESSAGE(ERR_ID, ERR_DESC, ID_LANG,REMARK,ISDATA,[TYPE], CREATED_BY, DT_CREATED) 
VALUES('MECHCLKINEXIST','Mechanic Clockin Exists.',1,'',0,1,'ADMIN', GETDATE())	

INSERT INTO TBL_MAS_ERR_MESSAGE(ERR_ID, ERR_DESC, ID_LANG,REMARK,ISDATA, [TYPE], CREATED_BY, DT_CREATED) 
VALUES('MECHCLKINEXIST','Mechanic Clockin Exists_N.',3,'',0,1,'ADMIN', GETDATE())	

INSERT INTO TBL_MAS_ERR_MESSAGE(ERR_ID, ERR_DESC, ID_LANG,REMARK,ISDATA, [TYPE], CREATED_BY, DT_CREATED) 
VALUES('MECHCLKINEXIST','Mechanic Clockin Exists_G.',2,'',0,1,'ADMIN', GETDATE())

GO