DECLARE @CNT AS INT  

IF NOT EXISTS (SELECT * FROM TBL_MAS_SETTINGS WHERE ID_CONFIG='MODEL' AND DESCRIPTION='KABRIOLET')
BEGIN
	SELECT @CNT = ISNULL(MAX(CAST(ID_SETTINGS AS INT)),0) FROM TBL_MAS_SETTINGS  
	INSERT INTO TBL_MAS_SETTINGS 
			(ID_SETTINGS,ID_CONFIG,DESCRIPTION,CREATED_BY,DT_CREATED)  
		VALUES  
			(@CNT+1,'MODEL','KABRIOLET','script',GETDATE())
END

IF NOT EXISTS (SELECT * FROM TBL_MAS_SETTINGS WHERE ID_CONFIG='MODEL' AND DESCRIPTION='KOMBIKUPE')
BEGIN
	SELECT @CNT = ISNULL(MAX(CAST(ID_SETTINGS AS INT)),0) FROM TBL_MAS_SETTINGS  
	INSERT INTO TBL_MAS_SETTINGS 
			(ID_SETTINGS,ID_CONFIG,DESCRIPTION,CREATED_BY,DT_CREATED)  
		VALUES  
			(@CNT+1,'MODEL','KOMBIKUPE','script',GETDATE())
END

IF NOT EXISTS (SELECT * FROM TBL_MAS_SETTINGS WHERE ID_CONFIG='MODEL' AND DESCRIPTION='STASJONSVOGN')
BEGIN
	SELECT @CNT = ISNULL(MAX(CAST(ID_SETTINGS AS INT)),0) FROM TBL_MAS_SETTINGS  
	INSERT INTO TBL_MAS_SETTINGS 
			(ID_SETTINGS,ID_CONFIG,DESCRIPTION,CREATED_BY,DT_CREATED)  
		VALUES  
			(@CNT+1,'MODEL','STASJONSVOGN','script',GETDATE())
END

IF NOT EXISTS (SELECT * FROM TBL_MAS_SETTINGS WHERE ID_CONFIG='MODEL' AND DESCRIPTION='SEDAN')
BEGIN
	SELECT @CNT = ISNULL(MAX(CAST(ID_SETTINGS AS INT)),0) FROM TBL_MAS_SETTINGS  
	INSERT INTO TBL_MAS_SETTINGS 
			(ID_SETTINGS,ID_CONFIG,DESCRIPTION,CREATED_BY,DT_CREATED)  
		VALUES  
			(@CNT+1,'MODEL','SEDAN','script',GETDATE())
END

IF NOT EXISTS (SELECT * FROM TBL_MAS_SETTINGS WHERE ID_CONFIG='MODEL' AND DESCRIPTION='DIV')
BEGIN
	SELECT @CNT = ISNULL(MAX(CAST(ID_SETTINGS AS INT)),0) FROM TBL_MAS_SETTINGS  
	INSERT INTO TBL_MAS_SETTINGS 
			(ID_SETTINGS,ID_CONFIG,DESCRIPTION,CREATED_BY,DT_CREATED)  
		VALUES  
			(@CNT+1,'MODEL','DIV','script',GETDATE())
END

			
						