INSERT INTO TBL_LA_ACCOUNT_MATRIX  
SELECT ID_Dept, ID_CUST_GRP, LA_Flg_DutyFree, 'RDC', LA_SaleAccCode, Project, LA_Flg_LedGL, 'REDCUTION', CREATED_BY, DT_CREATED, MODIFIED_BY, DT_MODIFIED, 
LA_DEPT_ACCCODE, LA_CUST_ACCCODE, LA_VATCODE
FROM TBL_LA_ACCOUNT_MATRIX WHERE LA_SALEDESCRIPTION='OR' AND ID_DEPT='22'
AND ID_CUST_GRP=9 AND LA_VATCODE='PLI'

DECLARE @LA_SLno INT

SELECT @LA_SLno=ID_SLNO FROM TBL_LA_ACCOUNT_MATRIX WHERE LA_SALEDESCRIPTION='RDC' AND ID_DEPT='22'
AND ID_CUST_GRP=9 AND LA_VATCODE='PLI'

INSERT INTO TBL_LA_ACCOUNT_MATRIX_DETAIL  
SELECT  @LA_SLno, 'SEGL', LA_FLG_CRE_DEB, LA_ACCOUNTNO, LA_DEPT_ACCOUNT_NO, LA_DIMENSION
FROM   TBL_LA_ACCOUNT_MATRIX_DETAIL
WHERE LA_SLno IN (SELECT ID_SLno FROM TBL_LA_ACCOUNT_MATRIX WHERE LA_SALEDESCRIPTION='OR' AND ID_DEPT='22'
AND ID_CUST_GRP=9 AND LA_VATCODE='PLI') AND LA_DESCRIPTION='SEGL'

INSERT INTO TBL_LA_ACCOUNT_MATRIX_DETAIL  
SELECT  @LA_SLno, 'SCGL', LA_FLG_CRE_DEB, LA_ACCOUNTNO, LA_DEPT_ACCOUNT_NO, LA_DIMENSION
FROM    TBL_LA_ACCOUNT_MATRIX_DETAIL
WHERE LA_SLno IN (SELECT ID_SLno FROM TBL_LA_ACCOUNT_MATRIX WHERE LA_SALEDESCRIPTION='OR' AND ID_DEPT='22'
AND ID_CUST_GRP=9 AND LA_VATCODE='PLI') AND LA_DESCRIPTION='SCGL'

