Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('btnAnnotation','Annotation_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('btnAnnotation','Anmerkning',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('btnAnnotation','Annotation',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('btnFetch','Fetch',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('btnFetch','Fetch_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('btnFetch','Hent',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('btnNote','Note',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('btnNote','Note_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('btnNote','Notat',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblAddedInterests','Added interests',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblAddedInterests','Added interests_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblAddedInterests','Påløpte renter',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblAddonGroup','Addon group',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblAddonGroup','Addon group_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblAddonGroup','Påkostgruppe',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblAssistSales','Assist on sale',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblAssistSales','Assist on sale_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblAssistSales','Bidrag ved salg',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblCallInDate','Call in date',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblCallInDate','Call in date_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblCallInDate','Innkallingsdato',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblCallInMonth','Call in month',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblCallInMonth','Call in month_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblCallInMonth','Innkalles',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblCallInService','Call in to service',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblCallInService','Call in to service_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblCallInService','Innkalles til service',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblCategory','Category',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblCategory','Category_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblCategory','Kategori',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblCleanedDate','Cleaned date',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblCleanedDate','Cleaned date_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblCleanedDate','Vasket dato',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblColor','Color',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblColor','Color_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblColor','Farge',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblCommitDays','Commit days',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblCommitDays','Commit days_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblCommitDays','Kommisjonsdager',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblContributionToday','Contribution per today',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblContributionToday','Contribution per today_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblContributionToday','Bidrag pr. dags dato',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblCostAfterSale','Cost after sale',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblCostAfterSale','Cost after sale_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblCostAfterSale','Påkost etter salg',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblCostBeforeSale','Cost before sale',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblCostBeforeSale','Cost before sale_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblCostBeforeSale','Påkost før salg',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblCostEquipment','Equipment costs',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblCostEquipment','Equipment costs_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblCostEquipment','Kost utstyr',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblCostFee','Cost fees',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblCostFee','Cost fees_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblCostFee','Inntaks salær',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblCostPriceNet','Cost price ex. vat',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblCostPriceNet','Cost price ex. vat_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblCostPriceNet','Inntakspris eks. mva',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblCosts','Costs',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblCosts','Costs_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblCosts','Selvkost',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblDateExpectedIn','Date expected in',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblDateExpectedIn','Date expected in_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblDateExpectedIn','Dato forventet inn',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblDeliveryDate','Delivery date',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblDeliveryDate','Delivery date_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblDeliveryDate','Leveringsdato',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblDeregDate','Dereg date',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblDeregDate','Dereg date_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblDeregDate','Avregdato',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblDetails','Details',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblDetails','Details_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblDetails','Detaljer',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblDeviationsPKK','Deviations PKK',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblDeviationsPKK','Deviations PKK_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblDeviationsPKK','Avvik PKK',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblDeviationsPKK','Deviations PKK',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblDeviationsPKK','Deviations PKK_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblDeviationsPKK','Avvik PKK',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblDeviationsPKK','Deviations PKK',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblDeviationsPKK','Deviations PKK_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblDeviationsPKK','Avvik PKK',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblDoNotCallPKK','Do not call in for PKK',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblDoNotCallPKK','Do not call in for PKK_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblDoNotCallPKK','Ikke innkall til PKK',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblDoorKey','Door key no',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblDoorKey','Door key no_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblDoorKey','Dørnøkkelnr',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblEarlierRegNumbers','Earlier registration numbers',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblEarlierRegNumbers','Earlier registration numbers_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblEarlierRegNumbers','Tidligere regnummer',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblEarlyRegNo1','Earlier regno 1',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblEarlyRegNo1','Earlier regno 1_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblEarlyRegNo1','Forrige regnr 1',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblEarlyRegNo2','Earlier regno 2',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblEarlyRegNo2','Earlier regno 2_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblEarlyRegNo2','Forrige regnr 2',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblEarlyRegNo3','Earlier regno 3',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblEarlyRegNo3','Earlier regno 3_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblEarlyRegNo3','Forrige regnr 3',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblEarlyRegNo4','Earlier regno 4',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblEarlyRegNo4','Earlier regno 4_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblEarlyRegNo4','Forrige regnr 4',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblEffectKw','Effect Kw',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblEffectKw','Effect Kw_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblEffectKw','Motorytelse',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblElCode','El.code',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblElCode','El.code_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblElCode','El.kode',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblEngineNumber','Engine No',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblEngineNumber','Engine No_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblEngineNumber','Motornummer',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblEUApprovalNumber','EU approval number',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblEUApprovalNumber','EU approval number_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblEUApprovalNumber','EU godkj. nr',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblForm','Form',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblForm','Form_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblForm','Kontroll skjema',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblFuelCard','Fuel card',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblFuelCard','Fuel card_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblFuelCard','Bensinkortnr',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblFuelCode','Fuel code',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblFuelCode','Fuel code_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblFuelCode','Drivstoff',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblGearbox','Gearbox',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblGearbox','Gearbox_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblGearbox','Girkasse',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblHours','Hours',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblHours','Hours_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblHours','Timer',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblHoursDate','Hours date',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblHoursDate','Hours date_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblHoursDate','Timer dato',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblInformation','Information',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblInformation','Information_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblInformation','Informasjon',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblInsurance','Insurance',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblInsurance','Insurance_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblInsurance','Forsikring',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblInsuranceBonus','Insurance bonus',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblInsuranceBonus','Insurance bonus_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblInsuranceBonus','Oppnådd bonus',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblInterorCode','Interior code',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblInterorCode','Interior code_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblInterorCode','Interiørkode',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblKeyNumber','Key number',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblKeyNumber','Key number_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblKeyNumber','Nøkkelnummer',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblKeyTagNumber','Key tag number',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblKeyTagNumber','Key tag number_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblKeyTagNumber','Nøkkeltaqgnr.',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblLastContactDate','Last contact date',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblLastContactDate','Last contact date_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblLastContactDate','Sist kontakt dato',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblLastInvoicedPKK','Last invoiced PKK',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblLastInvoicedPKK','Last invoiced PKK_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblLastInvoicedPKK','Siste PKK fakturert',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblLastPKKOk','Last PKK approved',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblLastPKKOk','Last PKK approved_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblLastPKKOk','Sist PKK godkjent',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblLastRegDate','Last regdate',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblLastRegDate','Last regdate_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblLastRegDate','Siste regdato',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblLength','Length',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblLength','Length_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblLength','Lengde',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblMachineHours','Machine W/Hours',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblMachineHours','Machine W/Hours_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblMachineHours','Maskin med timer',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblMakeCode','Make code',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblMakeCode','Make code_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblMakeCode','Fabrikatkode',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblMakeCode','Make Code',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblMakeCode','Fabrikmarkencode',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblMakeCode','Fabrikatkode',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblMaxRoofLoad','Max roof load',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblMaxRoofLoad','Max roof load_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblMaxRoofLoad','Maks taklast',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblMileage','Mileage',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblMileage','Mileage_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblMileage','KMStand',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblMileageDate','Mileage date',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblMileageDate','Mileage date_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblMileageDate','KMStand dato',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblModelForm','Model form',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblModelForm','Model form_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblModelForm','Karosseri',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblModelType','Model type',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblModelType','Model type_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblModelType','Modelltype',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblModelYear','Model year',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblModelYear','Model year_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblModelYear','Årsmodell',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblNetWeight','Net weight',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblNetWeight','Net weight_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblNetWeight','Nettovekt',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblNextPKK','Next PKK',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblNextPKK','Next PKK_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblNextPKK','Neste PKK',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblNOApprovalNumber','NO approval number',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblNOApprovalNumber','NO approval number_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblNOApprovalNumber','Norsk godkj. nr',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblPickNumber','Pick No',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblPickNumber','Pick No_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblPickNumber','Picknr',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblPistonDisp','Piston display',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblPistonDisp','Piston display_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblPistonDisp','Slagvolum',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblPracticalLoad','Practical load',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblPracticalLoad','Practical load_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblPracticalLoad','Nyttelast',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblPressureMechBrakes','Air pressure mechanical brakes',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblPressureMechBrakes','Air pressure mechanical brakes_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblPressureMechBrakes','Trykklyftmek. bremser',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblProductNumber','Product number',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblProductNumber','Product number_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblProductNumber','Produktnummer',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblProjectNumber','Project no',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblProjectNumber','Project no_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblProjectNumber','Prosjektnr',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblPurchaseOrder','Purchase order',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblPurchaseOrder','Purchase order_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblPurchaseOrder','Bestillingsnummer',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblQtyKeys','Number of keys',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblQtyKeys','Number of keys_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblQtyKeys','Ant. nøkler',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblRadioCode','Radio code',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblRadioCode','Radio code_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblRadioCode','Radiokode',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblRegDate','Reg date',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblRegDate','Reg date_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblRegDate','Regdato',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblRegDateNO','Reg date NO',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblRegDateNO','Reg date NO_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblRegDateNO','Regdato NO',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblRegistrationCosts','Registration costs',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblRegistrationCosts','Registration costs_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblRegistrationCosts','Reg. omkostninger',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblRegistrationFees','Registration fees',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblRegistrationFees','Registration fees_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblRegistrationFees','Reg. avgift',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblRegYear','RegYear',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblRegYear','RegYear_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblRegYear','Regår',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblRicambiNumber','Ricambi No',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblRicambiNumber','Ricambi No_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblRicambiNumber','Ricambinummer',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblRoundsMin','Rounds/Min',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblRoundsMin','Rounds/Min_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblRoundsMin','O/min',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblSalesEquipment','Sale equipment',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblSalesEquipment','Sale equipment_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblSalesEquipment','Salg utstyr',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblSalesFees','Sales fees',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblSalesFees','Sales fees_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblSalesFees','Salgs salær',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblSalesPriceExVat','Sales price ex. vat',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblSalesPriceExVat','Sales price ex. vat_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblSalesPriceExVat','Salgspris eks. mva',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblSalesPriceGross','Sales price gross',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblSalesPriceGross','Sales price gross_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblSalesPriceGross','Salgspris inkl. mva',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblSalesPriceNet','Sales price net',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblSalesPriceNet','Sales price net_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblSalesPriceNet','Netto salgspris',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblSalesProvision','Sales man provision',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblSalesProvision','Sales man provision_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblSalesProvision','Selger provisjon',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblServiceBook','Service book',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblServiceBook','Service book_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblServiceBook','Servicehefte',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblServiceCategory','Service category',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblServiceCategory','Service category_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblServiceCategory','Servicekategori',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblServiceDate','Service date',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblServiceDate','Service date_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblServiceDate','Servicedato',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblStartImobilizer','Start immobilizer',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblStartImobilizer','Start immobilizer_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblStartImobilizer','Startsperre',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblStdNoise','Std noise',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblStdNoise','Std noise_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblStdNoise','Std. støy',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblSubtractedCosts','- Costs',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblSubtractedCosts','- Costs_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblSubtractedCosts','- Selvkost',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblSubtractedDiscount','- Discount',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblSubtractedDiscount','- Discount_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblSubtractedDiscount','- Rabatt',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblTakenInDate','Taken in date',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblTakenInDate','Taken in date_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblTakenInDate','Inntaksdato',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblTechDocNumber','TechDoc No',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblTechDocNumber','TechDoc No_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblTechDocNumber','Techdocnr',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblTechnicalData','Technical data',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblTechnicalData','Technical data_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblTechnicalData','Tekniske data',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblTires','Tires',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblTires','Tires_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblTires','Dekk',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblTotalCost','Total costs',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblTotalCost','Total costs_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblTotalCost','Selvkost',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblTotalVehicleAmount','Total sales price',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblTotalVehicleAmount','Total sales price_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblTotalVehicleAmount','Total bilpris',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblTotWeight','Tot weight',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblTotWeight','Tot weight_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblTotWeight','Totalvekt',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblTowbar','Towbar',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblTowbar','Towbar_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblTowbar','Hengerfeste',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblUsedImported','Import used',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblUsedImported','Import used_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblUsedImported','Brukt importert',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblVanNumber','VAN number',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblVanNumber','VAN number_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblVanNumber','VAN nummer',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblVatFromSalesPrice','Vat from sales price',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblVatFromSalesPrice','Vat from sales price_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblVatFromSalesPrice','Mva av salgspris',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblVehicleDateMileage','Vehicle dates & mileage',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblVehicleDateMileage','Vehicle dates & mileage_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblVehicleDateMileage','Kjøretøydatoer og kmstand',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblVehicleDetails','Vehicle details',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblVehicleDetails','Vehicle details_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblVehicleDetails','Kjøretøydetaljer',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblVehicleGroup','Vehicle group',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblVehicleGroup','Vehicle group_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblVehicleGroup','Kjøretøygrp.',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblVehicleInformation','Vehicle information',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblVehicleInformation','Vehicle information_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblVehicleInformation','Kjøretøyinformasjon',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblVehicleModel','Vehicle model',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblVehicleModel','Vehicle model_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblVehicleModel','Kjøretøymodell',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblVehiclePrice','Vehicle price',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblVehiclePrice','Vehicle price_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblVehiclePrice','BILPRIS',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblVehicleType','Vehicle type',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblVehicleType','Vehicle type_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblVehicleType','Type',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblVinNumber','VIN No',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblVinNumber','VIN No_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblVinNumber','Chassinummer',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblWarehouseNumber','Warehouse',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblWarehouseNumber','Warehouse_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblWarehouseNumber','Lagersted',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblWarrantyCode','Warranty code',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblWarrantyCode','Warranty code_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblWarrantyCode','Garantikode',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblWidth','Width',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblWidth','Width_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblWidth','Bredde',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblWreckingAmount','Wrecking amount',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblWreckingAmount','Wrecking amount_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblWreckingAmount','Vrakpant',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblYearlyFee','Yearly fee',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblYearlyFee','Yearly fee_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblYearlyFee','Årsavgift',3,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblYearlyMileage','Yearly mileage',1,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblYearlyMileage','Yearly mileage_G',2,GETDATE(),'admin')
Insert into TBL_TAG_CAPTIONS (TAG,CAPTION,ID_LANG,DT_CREATED,CREATED_BY) values ('lblYearlyMileage','Årlig km. stand',3,GETDATE(),'admin')
