

IF NOT EXISTS(SELECT * FROM TBL_SPARES_RETURN_CODES WHERE RETURN_CODE='1')
BEGIN
	INSERT INTO TBL_SPARES_RETURN_CODES(RETURN_CODE,RETURN_DESCRIPTION)VALUES ('1','Feilbestilt av verksted')
	INSERT INTO TBL_SPARES_RETURN_CODES(RETURN_CODE,RETURN_DESCRIPTION)VALUES ('2','Feil innhold i esken')
	INSERT INTO TBL_SPARES_RETURN_CODES(RETURN_CODE,RETURN_DESCRIPTION)VALUES ('3','Feil levert av grossist')
	INSERT INTO TBL_SPARES_RETURN_CODES(RETURN_CODE,RETURN_DESCRIPTION)VALUES ('4','Feilplukk')
	INSERT INTO TBL_SPARES_RETURN_CODES(RETURN_CODE,RETURN_DESCRIPTION)VALUES ('5','Manko pa ordre')
	INSERT INTO TBL_SPARES_RETURN_CODES(RETURN_CODE,RETURN_DESCRIPTION)VALUES ('6','For mange valg i katalog')
	INSERT INTO TBL_SPARES_RETURN_CODES(RETURN_CODE,RETURN_DESCRIPTION)VALUES ('7','Feil pris')
	INSERT INTO TBL_SPARES_RETURN_CODES(RETURN_CODE,RETURN_DESCRIPTION)VALUES ('8','Pant')
	INSERT INTO TBL_SPARES_RETURN_CODES(RETURN_CODE,RETURN_DESCRIPTION)VALUES ('9','12 mnd. eller eldre')
	INSERT INTO TBL_SPARES_RETURN_CODES(RETURN_CODE,RETURN_DESCRIPTION)VALUES ('10','For mye levert')
	INSERT INTO TBL_SPARES_RETURN_CODES(RETURN_CODE,RETURN_DESCRIPTION)VALUES ('11','Defekt emballasje')
	INSERT INTO TBL_SPARES_RETURN_CODES(RETURN_CODE,RETURN_DESCRIPTION)VALUES ('12','Annet(bruk kommentar)')
END