Declare @menID int
Declare @modulID int


/* For adding New Parent Menu */
IF NOT EXISTS ( SELECT * FROM TBL_UTIL_MOD_DETAILS  WHERE NAME_SCR='Hotels' and NAME_MODULE ='HOTELS'  ) 
BEGIN
	INSERT INTO TBL_UTIL_MOD_DETAILS(NAME_SCR,NAME_URL,NAME_MODULE,Module_level,Flg) 
	VALUES('Hotels','','HOTELS',NULL,1)

	SET @menID = @@IDENTITY
END

/* For adding language to New Parent Menu */
IF NOT EXISTS(SELECT LANG_DESCRIPTION FROM TBL_UTIL_LANG_DETAILS WHERE ID_SCR = @menID)
BEGIN
	INSERT INTO TBL_UTIL_LANG_DETAILS VALUES(1,@menID,'Hotels')
	INSERT INTO TBL_UTIL_LANG_DETAILS VALUES(2,@menID,'Hotels')
	INSERT INTO TBL_UTIL_LANG_DETAILS VALUES(3,@menID,'Hoteller')

END

/* For adding New Child Menu */
IF NOT EXISTS(SELECT NAME_SCR FROM TBL_UTIL_MOD_DETAILS WHERE NAME_MODULE = 'TIRE HOTEL')
BEGIN
    Declare @menuID int
    Declare @moduleID int
    SELECT @moduleID = ID_SCR FROM TBL_UTIL_MOD_DETAILS WHERE NAME_SCR='Hotels' AND NAME_MODULE='HOTELS'
               
    INSERT INTO TBL_UTIL_MOD_DETAILS VALUES('Tire Hotel','/Transactions/TireHotel.aspx','HOTELS',@moduleID,1)
    SET @menuID =@@IDENTITY
    INSERT INTO TBL_UTIL_LANG_DETAILS VALUES(1,@menuID,'Tire Hotel')
    INSERT INTO TBL_UTIL_LANG_DETAILS VALUES(3,@menuID,'Dekkhotell')
    INSERT INTO TBL_UTIL_LANG_DETAILS VALUES(2,@menuID,'Reifenhotel')
END



GO
