
BEGIN
INSERT INTO TBL_WO_ORDER_STATUS (ORDER_STATUS_CODE,ORDER_STATUS_DESC,ORDER_STATUS_COLOR,CREATED_BY,DT_CREATED,FLG_USER_CREATED)
VALUES('NA','NEW APPOINTMENT','#C0C0C0','22admin',GETDATE(),0)
END