
--Script to insert existing Work Order Status to New Work Order Status with colours configuration

BEGIN
	INSERT INTO TBL_WO_ORDER_STATUS(ORDER_STATUS_CODE,ORDER_STATUS_DESC,ORDER_STATUS_COLOR,CREATED_BY,DT_CREATED)
	 SELECT c.Ctrl_value,C.CAPTION,'#FFFFFF','22admin',GETDATE() 
	 FROM TBL_DATA_CTRL_DETAILS C
	 INNER JOIN TBL_DATA_SCREEN_DETAILS S ON S.ID_SCRNO = C.ID_SCRNO
	 WHERE 
	 S.SCRN_NAME LIKE '%WOHEAD%' AND 
	 CNTRLNAME = 'CMBSTATUS' AND 
	 ID_LANG = 3 
	 ORDER BY CTRL_VALUE 
 END
