IF NOT EXISTS(SELECT * FROM syscolumns WHERE id=object_id('TBL_MAS_ITEM_MASTER') AND name='SUPP_CURRENTNO')
BEGIN 
ALTER TABLE TBL_MAS_ITEM_MASTER
ADD  SUPP_CURRENTNO VARCHAR(50)
END

IF NOT EXISTS(SELECT * FROM syscolumns WHERE id=object_id('TBL_MAS_ITEM_CATG') AND name='SUPP_CURRENTNO')
BEGIN 
ALTER TABLE TBL_MAS_ITEM_CATG
ADD  SUPP_CURRENTNO VARCHAR(50)
END

--Remove Foreign Key Constraint
ALTER TABLE TBL_WO_JOB_DEBITOR_DISCOUNT  
NOCHECK CONSTRAINT FK__TBL_WO_JOB_DEBIT__6F4A8121;

GO

UPDATE MIM
SET SUPP_CURRENTNO = SUP.SUPP_CURRENTNO
FROM TBL_MAS_SUPPLIER SUP
INNER JOIN TBL_MAS_ITEM_MASTER MIM
ON MIM.ID_SUPPLIER_ITEM = SUP.ID_SUPPLIER

GO
UPDATE MIC
SET SUPP_CURRENTNO = SUP.SUPP_CURRENTNO
FROM TBL_MAS_SUPPLIER SUP
INNER JOIN TBL_MAS_ITEM_CATG MIC
ON MIC.ID_SUPPLIER = SUP.ID_SUPPLIER
GO