USE [CARSDEV]
GO

/****** Object:  Table [dbo].[TBL_SPR_REPLACEMENT]    Script Date: 27.03.2020 12:27:39 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TBL_SPR_REPLACEMENT](
	[ID_REPLACEMENT] [int] IDENTITY(1,1) NOT NULL,
	[THIS_ID_ITEM] [varchar](30) NULL,
	[REPLACE_ID_ITEM] [varchar](30) NULL,
	[REPLACEMENTCODE] [varchar](50) NULL,
	[REPLACEMENTQTY] [decimal](13, 2) NULL,
	[REPLACEMENT_MAIN] [bit] NULL,
	[DESCRIPTION] [varchar](100) NULL,
	[CREATED_BY] [varchar](20) NOT NULL,
	[DT_CREATED] [datetime] NOT NULL,
	[MODIFIED_BY] [varchar](20) NULL,
	[DT_MODIFIED] [datetime] NULL,
	[THIS_SUPP_CURRENTNO] [varchar](10) NULL,
	[REPLACE_SUPP_CURRENTNO] [varchar](10) NULL,
 CONSTRAINT [PK_tbl_Replacement] PRIMARY KEY CLUSTERED 
(
	[ID_REPLACEMENT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

