

IF NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = N'TBL_MENU_CONFIG')
BEGIN
CREATE TABLE [dbo].[TBL_MENU_CONFIG](
	[ID_MENU_CONFIG] [int] IDENTITY(1,1) NOT NULL,
	[NAME_MODULE] [varchar](50) NOT NULL,
	[MENU_ORDER] [int] NOT NULL,
	[MENU_HEADER_ID] [int] NULL,
	[CREATED_BY] [varchar](20) NOT NULL,
	[DT_CREATED] [datetime] NOT NULL,
	[MODIFIED_BY] [varchar](20) NULL,
	[DT_MODIFIED] [datetime] NULL,
	[DISPLAYED] [bit] NULL,
 CONSTRAINT [PK_TBL_MENU_CONFIG] PRIMARY KEY CLUSTERED 
(
	[ID_MENU_CONFIG] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
	
END

 
IF NOT EXISTS(SELECT * FROM TBL_MENU_CONFIG WHERE NAME_MODULE ='CUSTOMER')
BEGIN
	INSERT INTO TBL_MENU_CONFIG
	(NAME_MODULE,MENU_ORDER,MENU_HEADER_ID,CREATED_BY,DT_CREATED,DISPLAYED)
	VALUES ('CUSTOMER',1,482,'22admin',GetDate(),1)
END

IF NOT EXISTS(SELECT * FROM TBL_MENU_CONFIG WHERE NAME_MODULE ='VEHICLE')
BEGIN
	INSERT INTO TBL_MENU_CONFIG
	(NAME_MODULE,MENU_ORDER,MENU_HEADER_ID,CREATED_BY,DT_CREATED,DISPLAYED)
	VALUES ('VEHICLE',2,481,'22admin',GetDate(),1)
END

IF NOT EXISTS(SELECT * FROM TBL_MENU_CONFIG WHERE NAME_MODULE ='SPARES')
BEGIN
	INSERT INTO TBL_MENU_CONFIG
	(NAME_MODULE,MENU_ORDER,MENU_HEADER_ID,CREATED_BY,DT_CREATED,DISPLAYED)
	VALUES ('SPARES',3,333,'22admin',GetDate(),1)
END

IF NOT EXISTS(SELECT * FROM TBL_MENU_CONFIG WHERE NAME_MODULE ='TIME REGISTRATION')
BEGIN
	INSERT INTO TBL_MENU_CONFIG
	(NAME_MODULE,MENU_ORDER,MENU_HEADER_ID,CREATED_BY,DT_CREATED,DISPLAYED)
	VALUES ('TIME REGISTRATION',4,230,'22admin',GetDate(),1)
END

IF NOT EXISTS(SELECT * FROM TBL_MENU_CONFIG WHERE NAME_MODULE ='WORK ORDER')
BEGIN
	INSERT INTO TBL_MENU_CONFIG
	(NAME_MODULE,MENU_ORDER,MENU_HEADER_ID,CREATED_BY,DT_CREATED,DISPLAYED)
	VALUES ('WORK ORDER',5,483,'22admin',GetDate(),1)
END

IF NOT EXISTS(SELECT * FROM TBL_MENU_CONFIG WHERE NAME_MODULE ='PLANNING')
BEGIN
	INSERT INTO TBL_MENU_CONFIG
	(NAME_MODULE,MENU_ORDER,MENU_HEADER_ID,CREATED_BY,DT_CREATED,DISPLAYED)
	VALUES ('PLANNING',6,215,'22admin',GetDate(),1)
END

IF NOT EXISTS(SELECT * FROM TBL_MENU_CONFIG WHERE NAME_MODULE ='CONFIGURATION')
BEGIN
	INSERT INTO TBL_MENU_CONFIG
	(NAME_MODULE,MENU_ORDER,MENU_HEADER_ID,CREATED_BY,DT_CREATED,DISPLAYED)
	VALUES ('CONFIGURATION',7,235,'22admin',GetDate(),0)
END

IF NOT EXISTS(SELECT * FROM TBL_MENU_CONFIG WHERE NAME_MODULE ='USER MANAGEMENT')
BEGIN
INSERT INTO TBL_MENU_CONFIG
(NAME_MODULE,MENU_ORDER,MENU_HEADER_ID,CREATED_BY,DT_CREATED,DISPLAYED)
VALUES ('USER MANAGEMENT',8,248,'22admin',GetDate(),0)
END

IF NOT EXISTS(SELECT * FROM TBL_MENU_CONFIG WHERE NAME_MODULE ='INTEGRATION')
BEGIN
	INSERT INTO TBL_MENU_CONFIG
	(NAME_MODULE,MENU_ORDER,MENU_HEADER_ID,CREATED_BY,DT_CREATED,DISPLAYED)
	VALUES ('INTEGRATION',9,463,'22admin',GetDate(),0)
END

IF NOT EXISTS(SELECT * FROM TBL_MENU_CONFIG WHERE NAME_MODULE ='HOTELS')
BEGIN
	INSERT INTO TBL_MENU_CONFIG
	(NAME_MODULE,MENU_ORDER,MENU_HEADER_ID,CREATED_BY,DT_CREATED,DISPLAYED)
	VALUES ('HOTELS',10,487,'22admin',GetDate(),1)
END

IF NOT EXISTS(SELECT * FROM TBL_MENU_CONFIG WHERE NAME_MODULE ='LA ACCOUNTING')
BEGIN
	INSERT INTO TBL_MENU_CONFIG
	(NAME_MODULE,MENU_ORDER,MENU_HEADER_ID,CREATED_BY,DT_CREATED,DISPLAYED)
	VALUES ('LA ACCOUNTING',11,489,'22admin',GetDate(),1)
END