

/****** Object:  Table [dbo].[TBL_APPOINTMENT_STATUS]    Script Date: 18-03-2021 20:20:38 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TBL_APPOINTMENT_STATUS](
	[ID_APPOINTMENT_STATUS] [int] IDENTITY(1,1) NOT NULL,
	[APPOINTMENT_STATUS_CODE] [varchar](10) NULL,
	[APPOINTMENT_STATUS_COLOR] [varchar](50) NULL,
	[CREATED_BY] [varchar](20) NULL,
	[DT_CREATED] [datetime] NULL,
	[MODIFIED_BY] [varchar](20) NULL,
	[DT_MODIFIED] [datetime] NULL,
 CONSTRAINT [PK_TBL_APPOINTMENT_STATUS] PRIMARY KEY CLUSTERED 
(
	[ID_APPOINTMENT_STATUS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


