
GO

/****** Object:  Table [dbo].[TBL_APPOINTMENT_DETAILS]    Script Date: 01-03-2021 12:15:32 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TBL_APPOINTMENT_DETAILS](
	[ID_APPOINTMENT_DETAILS] [int] IDENTITY(1,1) NOT NULL,
	[START_DATE] [datetime] NULL,
	[END_DATE] [datetime] NULL,
	[TEXT] [varchar](30) NULL,
	[DESCRIPTION] [varchar](50) NULL,
	[APPOINTMENT_ID] [int] NULL,
	[RESOURCE_ID] [varchar](40) NULL,
	[START_TIME] [datetime] NULL,
	[END_TIME] [datetime] NULL,
	[RESERVATION] [varchar](50) NULL,
	[SEARCH] [varchar](30) NULL,
	[MECHANIC] [varchar](30) NULL,
	[ID_WO_NO] [varchar](10) NULL,
	[ID_WO_PREFIX] [varchar](3) NULL,
	[ID_JOB] [int] NULL,
	[JOB_STATUS] [varchar](20) NULL,
	[CREATED_BY] [varchar](30) NULL,
	[DT_CREATED] [datetime] NULL,
	[MODIFIED_BY] [varchar](30) NULL,
	[DT_MODIFIED] [datetime] NULL,
	[RESOURCE_IDs] [varchar](200) NULL,
	[IS_OVER_TIME] [bit] NULL,
 CONSTRAINT [PK_APPOINTMENT_DETAILS] PRIMARY KEY CLUSTERED 
(
	[ID_APPOINTMENT_DETAILS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


ALTER TABLE [dbo].[TBL_APPOINTMENT_DETAILS]  WITH CHECK ADD  CONSTRAINT [FK_APPOINTMENT_DETAILS] FOREIGN KEY([APPOINTMENT_ID])
REFERENCES [dbo].[TBL_APPOINTMENTS_HEADER] ([APPOINTMENT_ID])
GO