GO

/****** Object:  Table [dbo].[TBL_APPOINTMENTS_HEADER]    Script Date: 01-03-2021 12:08:22 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TBL_APPOINTMENTS_HEADER](
	[APPOINTMENT_ID] [int] IDENTITY(1,1) NOT NULL,
	[APPOINTMENT_TYPE] [int] NULL,
	[START_DATE] [smalldatetime] NULL,
	[END_DATE] [smalldatetime] NULL,
	[SUBJECT] [nvarchar](50) NULL,
	[DESCRIPTION] [nvarchar](max) NULL,
	[STATUS] [int] NULL,
	[LABEL] [int] NULL,
	[RESOURCE_ID] [int] NULL,
	[RESOURCE_IDs] [nvarchar](max) NULL,
	[CUSTOMER_FIRST_NAME] [varchar](50) NULL,
	[CUSTOMER_MIDDLE_NAME] [varchar](50) NULL,
	[CUSTOMER_LAST_NAME] [varchar](50) NULL,
	[CUSTOMER_NUMBER] [varchar](30) NULL,
	[CUSTOMER_FIRM] [bit] NULL,
	[VEHICLE_REG_NO] [varchar](30) NULL,
	[VEHICLE_REF_NO] [varchar](30) NULL,
	[VEHICLE_CH_NO] [varchar](30) NULL,
	[VEHICLE_RENTAL_CAR] [bit] NULL,
	[VEHICLE_PERIODIC_CHECK] [bit] NULL,
	[VEHICLE_PERIODIC_SERVICE] [bit] NULL,
	[ID_WO_NO] [varchar](10) NULL,
	[ID_WO_PREFIX] [varchar](3) NULL,
	[WO_STATUS] [varchar](20) NULL,
	[CREATED_BY] [varchar](30) NULL,
	[DT_CREATED] [datetime] NULL,
	[MODIFIED_BY] [varchar](30) NULL,
	[DT_MODIFIED] [datetime] NULL,
	[ID_VEH_SEQ_WO] [int] NULL,
	[WO_VEH_MAK_MOD_MAP] [int] NULL,
	[WO_VEH_MOD] [varchar](50) NULL,
 CONSTRAINT [PK_APPOINTMENTS_HEADER] PRIMARY KEY CLUSTERED 
(
	[APPOINTMENT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO



