
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TBL_SPARES_RETURN_CODES](
	[ID_RETURN_CODE] [int] IDENTITY(1,1) NOT NULL,
	[RETURN_CODE] [varchar](30) NULL,
	[RETURN_DESCRIPTION] [varchar](50) NULL,
 CONSTRAINT [PK_TBL_SPARES_RETURN_CODES] PRIMARY KEY CLUSTERED 
(
	[ID_RETURN_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO


