USE [CARSDEV]
GO

/****** Object:  Table [dbo].[TBL_MAS_ITEM_MASTER]    Script Date: 27.03.2020 12:33:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TBL_MAS_ITEM_MASTER](
	[ID_ITEM] [varchar](30) NOT NULL,
	[ITEM_DESC] [varchar](100) NOT NULL,
	[ITEM_DESC_NAME2] [varchar](100) NULL,
	[ID_UNIT_ITEM] [varchar](10) NULL,
	[ID_MAKE] [varchar](10) NOT NULL,
	[ID_ITEM_MODEL] [varchar](10) NULL,
	[ID_ITEM_CATG] [varchar](10) NOT NULL,
	[ID_SUPPLIER_ITEM] [int] NULL,
	[ITEM_AVAIL_QTY] [decimal](15, 2) NULL,
	[ID_WH_ITEM] [int] NOT NULL,
	[ITEM_REORDER_LEVEL] [int] NULL,
	[ITEM_DISC_CODE] [int] NULL,
	[ITEM_DISC_CODE_BUY] [varchar](10) NULL,
	[BASIC_PRICE] [decimal](13, 2) NULL,
	[ITEM_PRICE] [decimal](13, 2) NULL,
	[COST_PRICE1] [decimal](13, 2) NULL,
	[NET_PRICE] [decimal](13, 2) NULL,
	[LOCATION] [varchar](20) NULL,
	[PACKAGE_QTY] [int] NULL,
	[ID_VAT_CODE] [varchar](10) NULL,
	[ACCOUNT_CODE] [varchar](20) NULL,
	[FLG_ALLOW_BCKORD] [bit] NULL,
	[FLG_CALC_PRICE] [bit] NULL,
	[FLG_CNT_STOCK] [bit] NULL,
	[FLG_DUTY] [bit] NULL,
	[CREATED_BY] [varchar](20) NOT NULL,
	[DT_CREATED] [datetime] NOT NULL,
	[MODIFIED_BY] [varchar](20) NULL,
	[DT_MODIFIED] [datetime] NULL,
	[Class_Code] [varchar](50) NULL,
	[ID_SPCATEGORY] [int] NULL,
	[AVG_PRICE] [decimal](13, 2) NULL,
	[QTY_NOT_DELIVERED] [decimal](12, 2) NULL,
	[QTY_BO_SUPPLIER] [decimal](12, 2) NULL,
	[LAST_BUY_PRICE] [decimal](13, 2) NULL,
	[DT_LAST_BUY] [datetime] NULL,
	[MIN_STOCK] [decimal](20, 2) NULL,
	[MAX_STOCK] [decimal](20, 2) NULL,
	[FLG_BLOCK_AUTO_ORD] [bit] NULL,
	[TD_CALC] [bit] NULL,
	[FLG_STOCKITEM] [bit] NULL,
	[VA_EXCHANGE_VEH] [bit] NULL,
	[VA_ORDER_COST] [bit] NULL,
	[FLG_STOCKITEM_STATUS] [bit] NULL,
	[ENV_ID_ITEM] [varchar](50) NULL,
	[ENV_ID_MAKE] [varchar](10) NULL,
	[ENV_ID_WAREHOUSE] [int] NULL,
	[FLG_EFD] [bit] NULL,
	[ALT_LOCATION] [varchar](50) NULL,
	[ANNOTATION] [varchar](150) NULL,
	[FLG_VAT_INCL] [bit] NULL,
	[FLG_OBTAIN_SPARE] [bit] NULL,
	[FLG_OBSOLETE_SPARE] [bit] NULL,
	[FLG_AUTOADJUST_PRICE] [bit] NULL,
	[FLG_LABELS] [bit] NULL,
	[FLG_ALLOW_DISCOUNT] [bit] NULL,
	[DISCOUNT] [decimal](18, 0) NULL,
	[LAST_COST_PRICE] [decimal](20, 2) NULL,
	[TEXT] [varchar](200) NULL,
	[FLG_AUTO_ARRIVAL] [bit] NULL,
	[FLG_REPLACEMENT_PURCHASE] [bit] NULL,
	[FLG_SAVE_TO_NONSTOCK] [bit] NULL,
	[WEIGHT] [varchar](50) NULL,
	[SUPP_CURRENTNO] [varchar](50) NOT NULL,
	[MAX_PURCHASE] [decimal](20, 2) NULL,
	[MIN_PURCHASE] [decimal](18, 2) NULL,
	[CONSUMPTION_ESTIMATED] [decimal](20, 2) NULL,
	[DEPOSITREFUND_ID_ITEM] [nchar](100) NULL,
	[DEPOSITREFUND_SUPP_CURRENTNO] [nchar](100) NULL,
	[BARCODE_NUMBER] [nchar](1000) NULL,
 CONSTRAINT [PK_TBL_MAS_ITEM_MASTER] PRIMARY KEY CLUSTERED 
(
	[ID_ITEM] ASC,
	[ID_MAKE] ASC,
	[ID_WH_ITEM] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[TBL_MAS_ITEM_MASTER]  WITH NOCHECK ADD  CONSTRAINT [FK_TBL_MAS_ITEM_MASTER_TBL_MAS_ITEM_CATG] FOREIGN KEY([ID_ITEM_CATG])
REFERENCES [dbo].[TBL_MAS_ITEM_CATG] ([ID_ITEM_CATG])
GO

ALTER TABLE [dbo].[TBL_MAS_ITEM_MASTER] CHECK CONSTRAINT [FK_TBL_MAS_ITEM_MASTER_TBL_MAS_ITEM_CATG]
GO

ALTER TABLE [dbo].[TBL_MAS_ITEM_MASTER]  WITH CHECK ADD  CONSTRAINT [FK_TBL_MAS_ITEM_MASTER_TBL_MAS_SUPPLIER] FOREIGN KEY([ID_SUPPLIER_ITEM], [SUPP_CURRENTNO])
REFERENCES [dbo].[TBL_MAS_SUPPLIER] ([ID_SUPPLIER], [SUPP_CURRENTNO])
GO

ALTER TABLE [dbo].[TBL_MAS_ITEM_MASTER] CHECK CONSTRAINT [FK_TBL_MAS_ITEM_MASTER_TBL_MAS_SUPPLIER]
GO

