USE [CARSDEV]
GO

/****** Object:  Table [dbo].[TBL_SPR_PO_HEADER]    Script Date: 31.01.2018 13:13:46 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TBL_SPR_PO_HEADER](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[PREFIX] [varchar](50) NOT NULL,
	[NUMBER] [varchar](50) NOT NULL,
	[ID_ORDERTYPE] [varchar](50) NOT NULL,
	[SUPP_CURRENTNO] [varchar](50) NOT NULL,
	[SUPP_NAME] [varchar](150) NULL,
	[ID_DEPT] [int] NOT NULL,
	[ID_WAREHOUSE] [int] NOT NULL,
	[CREATED_BY] [varchar](50) NOT NULL,
	[DT_CREATED] [datetime] NOT NULL,
	[DT_CREATED_SIMPLE] [int] NOT NULL,
	[MODIFIED_BY] [varchar](50) NULL,
	[DT_MODIFIED] [datetime] NULL,
	[DT_EXPECTED_DELIVERY] [bigint] NULL,
	[DELIVERY_METHOD] [int] NULL,
	[STATUS] [bit] NOT NULL,
	[FINISHED] [bit] NOT NULL,
	[ANNOTATION] [varchar](150) NULL,
 CONSTRAINT [PK_TBL_SPR_PURCHASEORDER_NEW] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[TBL_SPR_PO_HEADER]  WITH CHECK ADD  CONSTRAINT [FK_TBL_SPR_PURCHASEORDER_NEW_TBL_SPR_PURCHASEORDER_NEW] FOREIGN KEY([ID])
REFERENCES [dbo].[TBL_SPR_PO_HEADER] ([ID])
GO

ALTER TABLE [dbo].[TBL_SPR_PO_HEADER] CHECK CONSTRAINT [FK_TBL_SPR_PURCHASEORDER_NEW_TBL_SPR_PURCHASEORDER_NEW]
GO

