USE [CARSDEV]
GO

/****** Object:  Table [dbo].[TBL_MAS_CUSTOMER_GDPR]    Script Date: 26.08.2020 14.46.56 ******/
DROP TABLE [dbo].[TBL_MAS_CUSTOMER_GDPR]
GO

/****** Object:  Table [dbo].[TBL_MAS_CUSTOMER_GDPR]    Script Date: 26.08.2020 14.46.56 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[TBL_MAS_CUSTOMER_GDPR](
	[GDPR_ID] [int] IDENTITY(1,1) NOT NULL,
	[CUST_NO] [varchar](10) NOT NULL,
	[MANUAL_SMS] [bit] NULL,
	[MANUAL_MAIL] [bit] NULL,
	[PKK_SMS] [bit] NULL,
	[PKK_MAIL] [bit] NULL,
	[SERVICE_SMS] [bit] NULL,
	[SERVICE_MAIL] [bit] NULL,
	[BARGAIN_SMS] [bit] NULL,
	[BARGAIN_MAIL] [bit] NULL,
	[XTRACHECK_SMS] [bit] NULL,
	[XTRACHECK_MAIL] [bit] NULL,
	[REMINDER_SMS] [bit] NULL,
	[REMINDER_MAIL] [bit] NULL,
	[INFO_SMS] [bit] NULL,
	[INFO_MAIL] [bit] NULL,
	[FOLLOWUP_SMS] [bit] NULL,
	[FOLLOWUP_MAIL] [bit] NULL,
	[MARKETING_SMS] [bit] NULL,
	[MARKETING_MAIL] [bit] NULL,
	[DT_RESPONSE] [datetime] NULL,
	[DT_CREATED] [datetime] NOT NULL,
	[DT_CREATED_BY] varchar(20) NOT NULL,
	[DT_MODIFIED] [datetime] NULL,
	[DT_MODIFIED_BY] varchar(20) NULL
) ON [PRIMARY]
GO