USE [CARSDEV]
GO

/****** Object:  Table [dbo].[TBL_MAS_VEHICLE]    Script Date: 11.03.2016 09:51:43 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[TBL_MAS_VEHICLE](
	[ID_VEH_SEQ] [int] IDENTITY(1,1) NOT NULL,
	[VEH_REG_NO] [varchar](15) NULL,
	[VEH_INTERN_NO] [varchar](15) NULL,
	[VEH_VIN] [varchar](20) NULL,
	[ID_MAKE_VEH] [varchar](30) NOT NULL,
	[ID_MODEL_VEH] [varchar](10) NULL,
	[VEH_TYPE] [varchar](70) NULL,
	[DT_VEH_ERGN] [datetime] NULL,
	[VEH_MILEAGE] [int] NULL,
	[DT_VEH_MIL_REGN] [datetime] NULL,
	[VEH_HRS] [decimal](13, 0) NULL,
	[DT_VEH_HRS_ERGN] [datetime] NULL,
	[ID_MODEL_RP] [varchar](10) NULL,
	[VEH_MDL_YEAR] [int] NULL,
	[ID_GROUP_VEH] [varchar](10) NULL,
	[ID_CUSTOMER_VEH] [varchar](10) NULL,
	[VEH_DRIVER] [varchar](40) NULL,
	[VEH_MOBILE] [varchar](15) NULL,
	[VEH_PHONE1] [varchar](20) NULL,
	[VEH_DRV_IDEMIAL] [varchar](60) NULL,
	[VEH_FLG_SERVICE_PLAN] [bit] NULL,
	[VEH_FLG_ADDON] [bit] NULL,
	[ID_SER_TYP] [varchar](10) NULL,
	[ID_ADDON_LOCDEPT] [varchar](10) NULL,
	[VEH_ANNOT] [varchar](200) NULL,
	[ID_VAT_CD] [varchar](10) NULL,
	[CERATED_BY] [varchar](20) NOT NULL,
	[DT_CREATED] [datetime] NOT NULL,
	[MODIFIED_BY] [varchar](20) NULL,
	[DT_MODIFIED] [datetime] NULL,
	[COST_PRICE] [decimal](13, 2) NULL,
	[SELL_PRICE] [decimal](13, 2) NULL,
	[VA_ACC_CODE] [varchar](10) NULL,
	[PICK] [varchar](30) NULL,
	[VAN_NUM] [varchar](30) NULL,
	[VEH_REFNO] [varchar](30) NULL,
	[VEH_NEW_USED] [varchar](30) NULL,
	[VEH_STATUS] [varchar](30) NULL,
	[VEH_MODEL_TYPE] [varchar](30) NULL,
	[VEH_REGYEAR] [int] NULL,
	[VEH_REG_DATE_NO] [datetime] NULL,
	[VEH_LAST_REGDATE] [datetime] NULL,
	[VEH_DEREG_DATE] [datetime] NULL,
	[VEH_CATEGORY] [varchar](30) NULL,
	[VEH_MACHINE_W_HOURS] [bit] NULL,
	[VEH_COLOR] [varchar](30) NULL,
	[VEH_WARRANTY_CODE] [varchar](30) NULL,
	[VEH_NET_WEIGHT] [varchar](30) NULL,
	[VEH_TOT_WEIGHT] [varchar](30) NULL,
	[VEH_PROJECT_NO] [varchar](30) NULL,
	[VEH_LAST_CONTACT_DATE] [datetime] NULL,
	[VEH_PRACTICAL_LOAD] [varchar](30) NULL,
	[VEH_MAX_ROOF_LOAD] [varchar](30) NULL,
	[VEH_EARLIER_REGNO_1] [varchar](30) NULL,
	[VEH_EARLIER_REGNO_2] [varchar](30) NULL,
	[VEH_EARLIER_REGNO_3] [varchar](30) NULL,
	[VEH_EARLIER_REGNO_4] [varchar](30) NULL,
	[VEH_NOTE] [varchar](30) NULL,
	[VEH_MAKE_CODE] [varchar](30) NULL,
	[VEH_RICAMBI_NO] [varchar](30) NULL,
	[VEH_ENGINE_NO] [varchar](30) NULL,
	[VEH_FUEL_CODE] [varchar](30) NULL,
	[VEH_FUEL_CARD] [varchar](30) NULL,
	[VEH_GEAR_BOX] [varchar](30) NULL,
	[VEH_WAREHOUSE] [varchar](30) NULL,
	[VEH_KEYNO] [varchar](30) NULL,
	[VEH_DOOR_KEYNO] [varchar](30) NULL,
	[VEH_CONTROL_FORM] [varchar](30) NULL,
	[VEH_INTEROR_CODE] [varchar](30) NULL,
	[VEH_PURCHASE_NO] [varchar](30) NULL,
	[VEH_ADDON_GROUP] [varchar](30) NULL,
	[DT_VEH_EXPECTED_IN] [datetime] NULL,
	[VEH_TIRES] [varchar](30) NULL,
	[VEH_SERVICE_CATEGORY] [varchar](30) NULL,
	[VEH_NO_APPROVAL_NO] [varchar](30) NULL,
	[VEH_EU_APPROVAL_NO] [varchar](30) NULL,
	[VEH_PRODUCT_NO] [varchar](30) NULL,
	[VEH_EL_CODE] [varchar](30) NULL,
	[DT_VEH_TAKEN_IN] [datetime] NULL,
	[VEH_TAKEN_IN_MILEAGE] [int] NULL,
	[DT_VEH_DELIVERY] [datetime] NULL,
	[VEH_DELIVERY_MILEAGE] [int] NULL,
	[DT_VEH_SERVICE] [datetime] NULL,
	[VEH_SERVICE_MILEAGE] [int] NULL,
	[DT_VEH_CALL_IN] [datetime] NULL,
	[VEH_CALL_IN_MILEAGE] [int] NULL,
	[DT_VEH_CLEANED] [datetime] NULL,
	[VEH_TECHDOC_NO] [varchar](30) NULL,
	[VEH_LENGTH] [int] NULL,
	[VEH_WIDTH] [int] NULL,
	[VEH_NOISE] [varchar](30) NULL,
	[VEH_EFFECT_KW] [int] NULL,
	[VEH_PISTON_DISPLACEMENT] [varchar](30) NULL,
	[VEH_ROUNDS_PER_MIN] [varchar](30) NULL,
	[VEH_USED_IMPORTED] [bit] NULL,
	[VEH_PRESSURE_MECH_BRAKES] [bit] NULL,
	[VEH_TOWBAR] [bit] NULL,
	[VEH_SERVICE_BOOK] [bit] NULL,
	[DT_LAST_PKK_APPROVED] [datetime] NULL,
	[DT_NEXT_PKK] [datetime] NULL,
	[DT_LAST_PKK_INVOICED] [datetime] NULL,
	[VEH_CALL_IN_SERVICE] [bit] NULL,
	[VEH_CALL_IN_MONTH] [int] NULL,
	[VEH_CALL_IN_SERVICE_MILEAGE] [int] NULL,
	[VEH_DO_NOT_CALL_PKK] [bit] NULL,
	[VEH_DEVIATIONS_PKK] [varchar](30) NULL,
	[VEH_YEARLY_MILAGE] [int] NULL,
	[VEH_RADIO_CODE] [varchar](30) NULL,
	[VEH_START_IMMOBILIZER] [varchar](30) NULL,
	[VEH_QTY_KEYS] [int] NULL,
	[VEH_KEYTAG_NO] [varchar](30) NULL,
	[VEH_SALESPRICE_NET] [decimal](18, 2) NULL,
	[VEH_SALARY] [decimal](18, 2) NULL,
	[VEH_SALES_EQUIPMENT] [decimal](18, 2) NULL,
	[VEH_REG_COSTS] [decimal](18, 2) NULL,
	[VEH_DISCOUNT] [int] NULL,
	[VEH_NET_SALESPRICE] [decimal](18, 2) NULL,
	[VEH_FIX_COST] [decimal](18, 2) NULL,
	[VEH_ASSIST_SALE] [decimal](18, 2) NULL,
	[VEH_COST_AFTER_SALE] [decimal](18, 2) NULL,
	[VEH_CONTRIBUTION_TODAY] [decimal](18, 2) NULL,
	[VEH_SALESPRICE_GROSS] [decimal](18, 2) NULL,
	[VEH_REG_FEE] [decimal](18, 2) NULL,
	[VEH_VAT] [decimal](18, 2) NULL,
	[VEH_TOTAL_AMOUNT] [decimal](18, 2) NULL,
	[VEH_WRECKING_AMOUNT] [decimal](18, 2) NULL,
	[VEH_YEARLY_FEE] [decimal](18, 2) NULL,
	[VEH_INSURANCE] [decimal](18, 2) NULL,
	[VEH_COSTPRICE_NET] [decimal](18, 2) NULL,
	[VEH_INSURANCE_BONUS] [int] NULL,
	[VEH_COST_SALE] [decimal](18, 2) NULL,
	[VEH_COST_BEFORE_SALE] [decimal](18, 2) NULL,
	[VEH_SALES_PROVISION] [decimal](18, 2) NULL,
	[VEH_COMMIT_DAYS] [int] NULL,
	[VEH_ADDED_INTERESTS] [decimal](18, 2) NULL,
	[VEH_COST_EQUIPMENT] [decimal](18, 2) NULL,
	[VEH_TOTAL_COST] [decimal](18, 2) NULL,
	[VEH_CREDITNOTE_NO] [varchar](30) NULL,
	[DT_CREDITNOTE] [datetime] NULL,
	[VEH_INVOICE_NO] [varchar](30) NULL,
	[DT_INVOICE] [datetime] NULL,
	[DT_REBUY] [datetime] NULL,
	[VEH_REBUY_PRICE] [decimal](18, 2) NULL,
	[VEH_COST_PER_KM] [decimal](18, 2) NULL,
	[VEH_TURNOVER] [decimal](18, 2) NULL,
	[VEH_PROGRESS] [decimal](18, 2) NULL,
	[VEH_AXLE1] [varchar](50) NULL,
	[VEH_AXLE2] [varchar](50) NULL,
	[VEH_AXLE3] [varchar](50) NULL,
	[VEH_AXLE4] [varchar](50) NULL,
	[VEH_AXLE5] [varchar](50) NULL,
	[VEH_AXLE6] [varchar](50) NULL,
	[VEH_AXLE7] [varchar](50) NULL,
	[VEH_AXLE8] [varchar](50) NULL,
	[VEH_TRAILER_DESC] [varchar](100) NULL,
	[VEH_STD_TIRE_FRONT] [varchar](15) NULL,
	[VEH_STD_TIRE_BACK] [varchar](15) NULL,
	[VEH_MINLI_FRONT] [varchar](15) NULL,
	[VEH_MINLI_BACK] [varchar](15) NULL,
	[VEH_MIN_INPRESS_FRONT] [varchar](15) NULL,
	[VEH_MIN_INPRESS_BACK] [varchar](15) NULL,
	[VEH_STD_RIM_FRONT] [varchar](20) NULL,
	[VEH_STD_RIM_BACK] [varchar](20) NULL,
	[VEH_MIN_SPEED_FRONT] [varchar](15) NULL,
	[VEH_MIN_SPEED_BACK] [varchar](15) NULL,
	[VEH_MAX_TRACK_FRONT] [varchar](15) NULL,
	[VEH_MAX_TRACK_BACK] [varchar](15) NULL,
	[VEH_ALLOWABLE_WEIGHT_FRONT] [varchar](15) NULL,
	[VEH_ALLOWABLE_WEIGHT_BACK] [varchar](15) NULL,
	[VEH_QTY_AXLES] [varchar](15) NULL,
	[VEH_OPERATIVE_AXLES] [varchar](15) NULL,
	[VEH_DRIVE_WHEEL] [varchar](30) NULL,
	[VEH_TRAILER_WEIGHT_W_BRAKES] [varchar](20) NULL,
	[VEH_TRAILER_WEIGHT_WO_BRAKES] [varchar](20) NULL,
	[VEH_MAX_LOAD_TOWBAR] [varchar](20) NULL,
	[VEH_LENGTH_TO_TOWBAR] [varchar](20) NULL,
	[VEH_TOTAL_TRAILER_WEIGHT] [varchar](20) NULL,
	[VEH_SEATS] [varchar](20) NULL,
	[DT_VALID_FROM] [datetime] NULL,
	[VEH_EU_VERSION] [varchar](30) NULL,
	[VEH_EU_VARIANT] [varchar](30) NULL,
	[VEH_EURONORM] [varchar](30) NULL,
	[VEH_CO2_EMISSION] [varchar](20) NULL,
	[VEH_MAKE_PARTICLE_FILTER] [varchar](20) NULL,
	[VEH_CHASSI] [varchar](max) NULL,
	[VEH_IDENTITY] [varchar](max) NULL,
	[VEH_CERTIFICATE] [varchar](max) NULL,
	[VEH_ANNOTATIONS] [varchar](max) NULL,
 CONSTRAINT [PK_TBL_MAS_VEHICE] PRIMARY KEY CLUSTERED 
(
	[ID_VEH_SEQ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

