IF NOT EXISTS(SELECT * FROM syscolumns WHERE id=object_id('TBL_INV_DETAIL_LINES_LABOUR') AND name='ID_WOLAB_SEQ')
BEGIN 
ALTER TABLE TBL_INV_DETAIL_LINES_LABOUR
ADD ID_WOLAB_SEQ INT
END

GO

/*UPDATE ID_WOLAB_SEQ COLUMN ON TBL_INV_DETAIL_LINES_LABOUR*/
UPDATE LB
SET LB.ID_WOLAB_SEQ = WLB.ID_WOLAB_SEQ
FROM TBL_INV_DETAIL_LINES_LABOUR LB
INNER JOIN TBL_WO_LABOUR_DETAIL WLB ON WLB.ID_LOGIN=LB.INVL_IDLOGIN AND WLB.ID_WODET_SEQ=LB.ID_WODET_INVL

GO

UPDATE TBL_INV_DETAIL_LINES_LABOUR
SET ID_WOLAB_SEQ = 0
WHERE ID_WOLAB_SEQ IS NULL

GO

ALTER TABLE TBL_INV_DETAIL_LINES_LABOUR
ALTER COLUMN ID_WOLAB_SEQ INT NOT NULL

GO

/*UPDATE CONSTRAINT TBL_INV_DETAIL_LINES_LABOUR*/
ALTER TABLE TBL_INV_DETAIL_LINES_LABOUR
DROP CONSTRAINT PK_TBL_INV_DETAIL_LINES_LABOUR_1

ALTER TABLE TBL_INV_DETAIL_LINES_LABOUR
ADD CONSTRAINT PK_TBL_INV_DETAIL_LINES_LABOUR_1 PRIMARY KEY (ID_INV_NO, ID_WODET_INVL, INVL_IDLOGIN,ID_WOLAB_SEQ)

GO

