DECLARE @VEH_SCR_ID INT
DECLARE @CUS_SCR_ID INT
DECLARE @ORD_SCR_ID INT
DECLARE @VEH_SCH_SCR_ID INT
DECLARE @CUS_SCH_SCR_ID INT
DECLARE @ORD_SCH_SCR_ID INT

UPDATE TBL_UTIL_MOD_DETAILS
SET Name_url = ''
WHERE  NAME_SCR='Vehicle' and name_module = 'VEHICLE'

UPDATE TBL_UTIL_MOD_DETAILS
SET Name_url = ''
WHERE  NAME_SCR='Order' and name_module = 'WORK ORDER'

UPDATE TBL_UTIL_MOD_DETAILS
SET Name_url = ''
WHERE  NAME_SCR='Customer' and name_module = 'Customer'


SELECT @VEH_SCR_ID = ID_SCR FROM TBL_UTIL_MOD_DETAILS WHERE  NAME_SCR='VEHICLE' AND NAME_MODULE = 'VEHICLE'
SELECT @CUS_SCR_ID = ID_SCR FROM TBL_UTIL_MOD_DETAILS WHERE  NAME_SCR='CUSTOMER' AND NAME_MODULE = 'CUSTOMER'
SELECT @ORD_SCR_ID = ID_SCR FROM TBL_UTIL_MOD_DETAILS WHERE  NAME_SCR='ORDER' AND NAME_MODULE = 'WORK ORDER'


insert into TBL_UTIL_MOD_DETAILS values
('Vehicle Search','/master/frmVehicleInfo.aspx','VEHICLE',@VEH_SCR_ID,1)
insert into TBL_UTIL_MOD_DETAILS values
('Customer Search','/master/frmCustomerInfo.aspx','CUSTOMER',@CUS_SCR_ID,1)
insert into TBL_UTIL_MOD_DETAILS values
('Order Search','/Transactions/frmWOSearch.aspx','WORK ORDER',@ORD_SCR_ID,1)

SELECT @VEH_SCH_SCR_ID = ID_SCR FROM TBL_UTIL_MOD_DETAILS WHERE  NAME_SCR='Vehicle Search' AND NAME_MODULE = 'VEHICLE'
SELECT @CUS_SCH_SCR_ID = ID_SCR FROM TBL_UTIL_MOD_DETAILS WHERE  NAME_SCR='Customer Search' AND NAME_MODULE = 'CUSTOMER'
SELECT @ORD_SCH_SCR_ID = ID_SCR FROM TBL_UTIL_MOD_DETAILS WHERE  NAME_SCR='Order Search' AND NAME_MODULE = 'WORK ORDER'

insert into TBL_UTIL_LANG_DETAILS values(1,@VEH_SCH_SCR_ID,'Vehicle Search')
insert into TBL_UTIL_LANG_DETAILS values(2,@VEH_SCH_SCR_ID,'Vehicle Search_G')
insert into TBL_UTIL_LANG_DETAILS values(3,@VEH_SCH_SCR_ID,'Vehicle Search_N')

insert into TBL_UTIL_LANG_DETAILS values(1,@CUS_SCH_SCR_ID,'Customer Search')
insert into TBL_UTIL_LANG_DETAILS values(2,@CUS_SCH_SCR_ID,'Customer Search_G')
insert into TBL_UTIL_LANG_DETAILS values(3,@CUS_SCH_SCR_ID,'Customer Search_N')

insert into TBL_UTIL_LANG_DETAILS values(1,@ORD_SCH_SCR_ID,'Order Search')
insert into TBL_UTIL_LANG_DETAILS values(2,@ORD_SCH_SCR_ID,'Order Search_G')
insert into TBL_UTIL_LANG_DETAILS values(3,@ORD_SCH_SCR_ID,'Order Search_N')
