USE [CARSDEV]
GO
/****** Object:  StoredProcedure [dbo].[USP_GENERATE_XTRA_VEHICLES]    Script Date: 17.02.2022 12:41:57 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [dbo].[USP_GENERATE_XTRA_VEHICLES]
(
	
	@BADMOTOROIL int,
	@BADCFLEVEL int,
	@BADCFTEMP int,
	@BADBRAKEFLUID int,
	@BADBATTERY int,
	@BADVIPESFRONT int,
	@BADVIPESREAR int,
	@BADLIGHTSFRONT int,
	@BADLIGHTSREAR int,
	@BADSHOCKABSORBERFRONT int,
	@BADSHOCKABSORBERREAR int,
	@BADTIRESFRONT int,
	@BADTIRESREAR int,
	@BADSUSPENSIONFRONT int,
	@BADSUSPENSIONREAR int,
	@BADBRAKESFRONT int,
	@BADBRAKESREAR int,
	@BADEXHAUST int,
	@BADSEALEDENGINE int,
	@BADSEALEDGEARBOX int,
	@BADWINDSHIELD int,


	@MEDIUMMOTOROIL int,
	@MEDIUMCFLEVEL int,
	@MEDIUMCFTEMP int,
	@MEDIUMBRAKEFLUID int,
	@MEDIUMBATTERY int,
	@MEDIUMVIPESFRONT int,
	@MEDIUMVIPESREAR int,
	@MEDIUMLIGHTSFRONT int,
	@MEDIUMLIGHTSREAR int,
	@MEDIUMSHOCKABSORBERFRONT int,
	@MEDIUMSHOCKABSORBERREAR int,
	@MEDIUMTIRESFRONT int,
	@MEDIUMTIRESREAR int,
	@MEDIUMSUSPENSIONFRONT int,
	@MEDIUMSUSPENSIONREAR int,
	@MEDIUMBRAKESFRONT int,
	@MEDIUMBRAKESREAR int,
	@MEDIUMEXHAUST int,
	@MEDIUMSEALEDENGINE int,
	@MEDIUMSEALEDGEARBOX int,
	@MEDIUMWINDSHIELD int
	
)
AS
BEGIN
DECLARE @MAINQRY AS NVARCHAR(MAX)
DECLARE @CQRY AS NVARCHAR(MAX) = ''
--DECLARE @THE_PRICETYPE varchar(60)

--SELECT @THE_PRICETYPE = PRICETYPE 
--FROM TBL_SPR_SUPPLIERCONFIG
--WHERE ((SUPP_CURRENTNO LIKE @SUPP_CURRENTNO) AND SUPP_ORDERTYPE LIKE @ID_ORDERTYPE)
--print(@THE_PRICETYPE)
--SELECT * FROM TBL_MAS_VEHICLE
--SELECT * FROM TBL_MAS_CUSTOMER
--SELECT * FROM TBL_MAS_CUSTOMER_CONTACT WHERE CONTACT_TYPE='1' AND CONTACT_STANDARD='1'
--SELECT * FROM TBL_MAS_VEHICLE_XTRACHECK

SET @MAINQRY = N'SELECT VX.REFNR, 
VX.REGISTRATIONNR, 
MV.ID_MAKE_VEH, 
MV.VEH_TYPE, 
MV.ID_CUSTOMER_VEH, 
MC.CUST_NAME, 
CC.CONTACT_VALUE ,
(SELECT CONTACT_VALUE FROM TBL_MAS_CUSTOMER_CONTACT WHERE CONTACT_CUSTOMER_ID = MV.ID_CUSTOMER_VEH AND CONTACT_TYPE=6 AND CONTACT_STANDARD=1) AS MAIL
FROM TBL_MAS_VEHICLE_XTRACHECK VX
INNER JOIN TBL_MAS_VEHICLE MV ON MV.VEH_INTERN_NO = VX.REFNR
INNER JOIN TBL_MAS_CUSTOMER MC ON MC.ID_CUSTOMER = MV.ID_CUSTOMER_VEH
INNER JOIN TBL_MAS_CUSTOMER_CONTACT CC ON CC.CONTACT_CUSTOMER_ID = MC.ID_CUSTOMER AND CC.CONTACT_TYPE=1 AND CC.CONTACT_STANDARD=1
WHERE '


	IF @BADMOTOROIL = 2 AND @MEDIUMMOTOROIL = 1
		SET @CQRY = '(VX.MOTOROIL >= 1) '
	ELSE IF  @BADMOTOROIL = 0 AND @MEDIUMMOTOROIL = 1
		SET @CQRY = 'VX.MOTOROIL = 1 '
	ELSE IF  @BADMOTOROIL = 2 AND @MEDIUMMOTOROIL = 0 
		SET @CQRY = 'VX.MOTOROIL = 2 ' 
	ELSE
		SET @CQRY = 'VX.MOTOROIL = 0 '

	IF @BADCFLEVEL = 2 AND @MEDIUMCFLEVEL = 1
		SET @CQRY = @CQRY + 'OR VX.[FREEZE-LEVEL] >= 1 '
	ELSE IF  @BADCFLEVEL = 0 AND @MEDIUMCFLEVEL = 1
		SET @CQRY = @CQRY + 'OR VX.[FREEZE-LEVEL] = 1 '
	ELSE IF  @BADCFLEVEL = 2 AND @MEDIUMCFLEVEL = 0 
		SET @CQRY = @CQRY + 'OR VX.[FREEZE-LEVEL] = 2 ' 

	IF @BADCFTEMP = 2 AND @MEDIUMCFTEMP = 1
		SET @CQRY = @CQRY + 'OR VX.[FREEZE-POINT] >= 1 '
	ELSE IF  @BADCFTEMP = 0 AND @MEDIUMCFTEMP = 1
		SET @CQRY = @CQRY + 'OR VX.[FREEZE-POINT] = 1 '
	ELSE IF  @BADCFTEMP = 2 AND @MEDIUMCFTEMP = 0 
		SET @CQRY = @CQRY + 'OR VX.[FREEZE-POINT] = 2 '
	
	IF @BADBRAKEFLUID = 2 AND @MEDIUMBRAKEFLUID = 1
		SET @CQRY = @CQRY + 'OR VX.BRAKEFLUID >= 1 '
	ELSE IF  @BADBRAKEFLUID = 0 AND @MEDIUMBRAKEFLUID = 1
		SET @CQRY = @CQRY + 'OR VX.BRAKEFLUID = 1 '
	ELSE IF  @BADBRAKEFLUID = 2 AND @MEDIUMBRAKEFLUID = 0 
		SET @CQRY = @CQRY + 'OR VX.BRAKEFLUID = 2 '

	IF @BADBATTERY = 2 AND @MEDIUMBATTERY = 1
		SET @CQRY = @CQRY + 'OR VX.BATTERY >= 1 '
	ELSE IF  @BADBATTERY = 0 AND @MEDIUMBATTERY = 1
		SET @CQRY = @CQRY + 'OR VX.BATTERY = 1 '
	ELSE IF  @BADBATTERY = 2 AND @MEDIUMBATTERY = 0 
		SET @CQRY = @CQRY + 'OR VX.BATTERY = 2 '

	IF @BADVIPESFRONT = 2 AND @MEDIUMVIPESFRONT = 1
		SET @CQRY = @CQRY + 'OR VX.[WINDSCREEN-WIPER-FRONT] >= 1 '
	ELSE IF  @BADVIPESFRONT = 0 AND @MEDIUMVIPESFRONT = 1
		SET @CQRY = @CQRY + 'OR VX.[WINDSCREEN-WIPER-FRONT] = 1 '
	ELSE IF  @BADVIPESFRONT = 2 AND @MEDIUMVIPESFRONT = 0 
		SET @CQRY = @CQRY + 'OR VX.[WINDSCREEN-WIPER-FRONT] = 2 '

	IF @BADVIPESREAR = 2 AND @MEDIUMVIPESREAR = 1
		SET @CQRY = @CQRY + 'OR VX.[WINDSCREEN-WIPER-REAR] >= 1 '
	ELSE IF  @BADVIPESREAR = 0 AND @MEDIUMVIPESREAR = 1
		SET @CQRY = @CQRY + 'OR VX.[WINDSCREEN-WIPER-REAR] = 1 '
	ELSE IF  @BADVIPESREAR = 2 AND @MEDIUMVIPESREAR = 0 
		SET @CQRY = @CQRY + 'OR VX.[WINDSCREEN-WIPER-REAR] = 2 '

	IF @BADLIGHTSFRONT = 2 AND @MEDIUMLIGHTSFRONT = 1
		SET @CQRY = @CQRY + 'OR VX.[LIGHT-BULB-FRONT] >= 1 '
	ELSE IF  @BADLIGHTSFRONT = 0 AND @MEDIUMLIGHTSFRONT = 1
		SET @CQRY = @CQRY + 'OR VX.[LIGHT-BULB-FRONT] = 1 '
	ELSE IF  @BADLIGHTSFRONT = 2 AND @MEDIUMLIGHTSFRONT = 0 
		SET @CQRY = @CQRY + 'OR VX.[LIGHT-BULB-FRONT] = 2 '
	
	IF @BADLIGHTSREAR = 2 AND @MEDIUMLIGHTSREAR = 1
		SET @CQRY = @CQRY + 'OR VX.[LIGHT-BULB-REAR] >= 1 '
	ELSE IF  @BADLIGHTSREAR = 0 AND @MEDIUMLIGHTSREAR = 1
		SET @CQRY = @CQRY + 'OR VX.[LIGHT-BULB-REAR] = 1 '
	ELSE IF  @BADLIGHTSREAR = 2 AND @MEDIUMLIGHTSREAR = 0 
		SET @CQRY = @CQRY + 'OR VX.[LIGHT-BULB-REAR] = 2 '

	IF @BADSHOCKABSORBERFRONT = 2 AND @MEDIUMSHOCKABSORBERFRONT = 1
		SET @CQRY = @CQRY + 'OR VX.[SHOCK-ABSORBER-FRONT] >= 1 '
	ELSE IF  @BADSHOCKABSORBERFRONT = 0 AND @MEDIUMSHOCKABSORBERFRONT = 1
		SET @CQRY = @CQRY + 'OR VX.[SHOCK-ABSORBER-FRONT] = 1 '
	ELSE IF  @BADSHOCKABSORBERFRONT = 2 AND @MEDIUMSHOCKABSORBERFRONT = 0 
		SET @CQRY = @CQRY + 'OR VX.[SHOCK-ABSORBER-FRONT] = 2 '
	
	IF @BADSHOCKABSORBERREAR = 2 AND @MEDIUMSHOCKABSORBERREAR = 1
		SET @CQRY = @CQRY + 'OR VX.[SHOCK-ABSORBER-REAR] >= 1 '
	ELSE IF  @BADSHOCKABSORBERREAR = 0 AND @MEDIUMSHOCKABSORBERREAR = 1
		SET @CQRY = @CQRY + 'OR VX.[SHOCK-ABSORBER-REAR] = 1 '
	ELSE IF  @BADSHOCKABSORBERREAR = 2 AND @MEDIUMSHOCKABSORBERREAR = 0 
		SET @CQRY = @CQRY + 'OR VX.[SHOCK-ABSORBER-REAR] = 2 '

	IF @BADTIRESFRONT = 2 AND @MEDIUMTIRESFRONT = 1
		SET @CQRY = @CQRY + 'OR VX.[TIRE-FRONT] >= 1 '
	ELSE IF  @BADTIRESFRONT = 0 AND @MEDIUMTIRESFRONT = 1
		SET @CQRY = @CQRY + 'OR VX.[TIRE-FRONT] = 1 '
	ELSE IF  @BADTIRESFRONT = 2 AND @MEDIUMTIRESFRONT = 0 
		SET @CQRY = @CQRY + 'OR VX.[TIRE-FRONT] = 2 '
	
	IF @BADTIRESREAR = 2 AND @MEDIUMTIRESREAR = 1
		SET @CQRY = @CQRY + 'OR VX.[TIRE-REAR] >= 1 '
	ELSE IF  @BADTIRESREAR = 0 AND @MEDIUMTIRESREAR = 1
		SET @CQRY = @CQRY + 'OR VX.[TIRE-REAR] = 1 '
	ELSE IF  @BADTIRESREAR = 2 AND @MEDIUMTIRESREAR = 0 
		SET @CQRY = @CQRY + 'OR VX.[TIRE-REAR] = 2 '

	IF @BADSUSPENSIONFRONT = 2 AND @MEDIUMSUSPENSIONFRONT = 1
		SET @CQRY = @CQRY + 'OR VX.[SUSPENSION-FRONT] >= 1 '
	ELSE IF  @BADSUSPENSIONFRONT = 0 AND @MEDIUMSUSPENSIONFRONT = 1
		SET @CQRY = @CQRY + 'OR VX.[SUSPENSION-FRONT] = 1 '
	ELSE IF  @BADSUSPENSIONFRONT = 2 AND @MEDIUMSUSPENSIONFRONT = 0 
		SET @CQRY = @CQRY + 'OR VX.[SUSPENSION-FRONT] = 2 '
	
	IF @BADSUSPENSIONREAR = 2 AND @MEDIUMSUSPENSIONREAR = 1
		SET @CQRY = @CQRY + 'OR VX.[SUSPENSION-REAR] >= 1 '
	ELSE IF  @BADSUSPENSIONREAR = 0 AND @MEDIUMSUSPENSIONREAR = 1
		SET @CQRY = @CQRY + 'OR VX.[SUSPENSION-REAR] = 1 '
	ELSE IF  @BADSUSPENSIONREAR = 2 AND @MEDIUMSUSPENSIONREAR = 0 
		SET @CQRY = @CQRY + 'OR VX.[SUSPENSION-REAR] = 2 '

	IF @BADBRAKESFRONT = 2 AND @MEDIUMBRAKESFRONT = 1
		SET @CQRY = @CQRY + 'OR VX.[BRAKES-FRONT] >= 1 '
	ELSE IF  @BADBRAKESFRONT = 0 AND @MEDIUMBRAKESFRONT = 1
		SET @CQRY = @CQRY + 'OR VX.[BRAKES-FRONT] = 1 '
	ELSE IF  @BADBRAKESFRONT = 2 AND @MEDIUMBRAKESFRONT = 0 
		SET @CQRY = @CQRY + 'OR VX.[BRAKES-FRONT] = 2 '
	
	IF @BADBRAKESREAR = 2 AND @MEDIUMBRAKESREAR = 1
		SET @CQRY = @CQRY + 'OR VX.[BRAKES-REAR] >= 1 '
	ELSE IF  @BADBRAKESREAR = 0 AND @MEDIUMBRAKESREAR = 1
		SET @CQRY = @CQRY + 'OR VX.[BRAKES-REAR] = 1 '
	ELSE IF  @BADBRAKESREAR = 2 AND @MEDIUMBRAKESREAR = 0 
		SET @CQRY = @CQRY + 'OR VX.[BRAKES-REAR] = 2 '
	
	IF @BADEXHAUST = 2 AND @MEDIUMEXHAUST = 1
		SET @CQRY = @CQRY + 'OR VX.[EXHAUST] >= 1 '
	ELSE IF  @BADEXHAUST = 0 AND @MEDIUMEXHAUST = 1
		SET @CQRY = @CQRY + 'OR VX.[EXHAUST] = 1 '
	ELSE IF  @BADEXHAUST = 2 AND @MEDIUMEXHAUST = 0 
		SET @CQRY = @CQRY + 'OR VX.[EXHAUST] = 2 '

	IF @BADSEALEDENGINE = 2 AND @MEDIUMSEALEDENGINE = 1
		SET @CQRY = @CQRY + 'OR VX.[DENSITY-MOTOR] >= 1 '
	ELSE IF  @BADSEALEDENGINE = 0 AND @MEDIUMSEALEDENGINE = 1
		SET @CQRY = @CQRY + 'OR VX.[DENSITY-MOTOR] = 1 '
	ELSE IF  @BADSEALEDENGINE = 2 AND @MEDIUMSEALEDENGINE = 0 
		SET @CQRY = @CQRY + 'OR VX.[DENSITY-MOTOR] = 2 '

	IF @BADSEALEDGEARBOX = 2 AND @MEDIUMSEALEDGEARBOX = 1
		SET @CQRY = @CQRY + 'OR VX.[DENSITY-GEARBOX] >= 1 '
	ELSE IF  @BADSEALEDGEARBOX = 0 AND @MEDIUMSEALEDGEARBOX = 1
		SET @CQRY = @CQRY + 'OR VX.[DENSITY-GEARBOX] = 1 '
	ELSE IF  @BADSEALEDGEARBOX = 2 AND @MEDIUMSEALEDGEARBOX = 0 
		SET @CQRY = @CQRY + 'OR VX.[DENSITY-GEARBOX] = 2 '

	IF @BADWINDSHIELD = 2 AND @MEDIUMWINDSHIELD = 1
		SET @CQRY = @CQRY + 'OR VX.WINDSCREEN >= 1 '
	ELSE IF  @BADWINDSHIELD = 0 AND @MEDIUMWINDSHIELD = 1
		SET @CQRY = @CQRY + 'OR VX.WINDSCREEN = 1 '
	ELSE IF  @BADWINDSHIELD = 2 AND @MEDIUMWINDSHIELD = 0 
		SET @CQRY = @CQRY + 'OR VX.WINDSCREEN = 2 '

	IF @CQRY <> ''
		SET @MAINQRY = @MAINQRY + @CQRY
		print @MAINQRY

	EXEC (@MAINQRY) 	

  

 
END


--SET @MAINQRY = N'SELECT IM.ID_ITEM
--	, IM.ITEM_DESC
--	, (SELECT CATG_DESC FROM TBL_MAS_ITEM_CATG IC WHERE IC.ID_ITEM_CATG = IM.ID_ITEM_CATG) AS ITEM_CATG_DESC 
--	,IM.ID_WH_ITEM
--	,IM.ID_ITEM_CATG
--	,IM.ITEM_AVAIL_QTY AS STOCKBEFORECOUNT
--	,ISNULL(IM.LOCATION, '''') as LOCATION
--	,(SELECT ISNULL((SELECT TOP (1) CO.LAST_COUNTED_DATE FROM TBL_SPR_COUNTING CO WHERE CO.ID_ITEM = IM.ID_ITEM AND CO.ID_WH = IM.ID_WH_ITEM and co.SUPP_CURRENTNO = im.SUPP_CURRENTNO ORDER BY LAST_COUNTED_DATE DESC), NULL)) AS LAST_COUNTED_DATE
--	,(SELECT ISNULL((SELECT TOP (1) COALESCE(CO.CREATED_BY, '''') FROM TBL_SPR_COUNTING CO WHERE CO.ID_ITEM = IM.ID_ITEM AND CO.ID_WH = IM.ID_WH_ITEM and co.SUPP_CURRENTNO = im.SUPP_CURRENTNO ORDER BY DT_CREATED DESC), '''')) AS CREATED_BY
--	,IM.SUPP_CURRENTNO
--	,IM.AVG_PRICE
--	,IM.ITEM_PRICE
--	,IM.COST_PRICE1
--	FROM TBL_MAS_ITEM_MASTER IM
--	WHERE IM.ID_WH_ITEM ='+ CONVERT(VARCHAR(10),@warehouseId)+' AND NOT IM.ID_ITEM IN (SELECT ID_ITEM FROM TBL_SPR_COUNTING WHERE CLOSED = 0)'




--IF @sparefrom <> '' AND @spareto <> '' 
--		SET @CQRY = @CQRY + ' AND (IM.ID_ITEM between ''' + @sparefrom + '%'' AND ''' + @spareTo + '%'')'
						                                        

--	IF @locationFrom <> '' AND @locationTo <> ''
--		SET @CQRY = @CQRY + ' AND (IM.LOCATION between ''' + @locationFrom + '%'' AND ''' + @locationTo + '%'')'


--	IF @stock = 1
--		SET @CQRY = @CQRY + ' AND IM.ITEM_AVAIL_QTY > 0'
	
--	IF @nolocation = 1
--		SET @CQRY = @CQRY + ' AND IM.LOCATION IS NULL OR IM.LOCATION = '''''
		
	
--	IF @sortBy = '1' 
--		SET @CQRY = @CQRY +  ' ORDER BY IM.ID_ITEM ASC'

--	ELSE IF @sortBy = '2' 
--		SET @CQRY = @CQRY +  ' ORDER BY IM.ITEM_DESC ASC'

--	ELSE IF @sortBy = '3' 
--		SET @CQRY = @CQRY +  ' ORDER BY IM.LOCATION ASC'