USE [CARSDEV]
GO
/****** Object:  StoredProcedure [dbo].[USP_CUSTOMER_CONTACT_PERSON_FETCH]    Script Date: 25.08.2020 10.16.08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[USP_CUSTOMER_CONTACT_PERSON_FETCH] (
	@ID_CP				VARCHAR(50) = NULL
	,@CP_CUSTOMER_ID	VARCHAR(50) = NULL
	--,@RETVAL			VARCHAR(10) OUTPUT
)
AS
DECLARE @CUSTOMER_CONTACT_PERSON INT
SET @CUSTOMER_CONTACT_PERSON = (SELECT ID_CP FROM TBL_MAS_CUSTOMER WHERE ID_CUSTOMER = @CP_CUSTOMER_ID)
DECLARE @CUSTOMER_CONTACT_TITLE_DESC VARCHAR(100)
SET @CUSTOMER_CONTACT_TITLE_DESC = (SELECT CPT.TITLE_DESCRIPTION FROM TBL_MAS_CUSTOMER_CONTACT_PERSON CP INNER JOIN TBL_MAS_CUSTOMER_CONTACT_PERSON_TITLE CPT ON CPT.TITLE_CODE = CP.CP_TITLE_CODE WHERE CP.ID_CP = @CUSTOMER_CONTACT_PERSON)
SELECT [ID_CP]
      ,[CP_CUSTOMER_ID]
      ,[CP_FIRST_NAME]
      ,[CP_MIDDLE_NAME]
      ,[CP_LAST_NAME]
      ,[CP_PERM_ADD]
      ,[CP_VISIT_ADD]
      ,[CP_ZIP_CODE]
      ,[CP_ZIP_CITY]
      ,[CP_EMAIL]
      ,[CP_PHONE_PRIVATE]
      ,[CP_PHONE_MOBILE]
      ,[CP_PHONE_FAX]
      ,[CP_PHONE_WORK]
      ,[CP_BIRTH_DATE]
      ,[CP_TITLE_CODE]
	  ,@CUSTOMER_CONTACT_TITLE_DESC AS TITLE_DESC
      ,[CP_FUNCTION_CODE]
      ,[CP_CONTACT]
      ,[CP_CAR_USER]
      ,[CP_EMAIL_REF]
      ,[CP_NOTES]
      ,[CREATED_BY]
      ,[DT_CREATED]
      ,[MODIFIED_BY]
      ,[DT_MODIFIED]
	  ,@CUSTOMER_CONTACT_PERSON as [CUSTOMER_CONTACT_PERSON]
  FROM [dbo].[TBL_MAS_CUSTOMER_CONTACT_PERSON]
  WHERE 
	CAST(ID_CP as varchar) LIKE
	CASE WHEN @ID_CP IS NULL THEN
		'%'
	ELSE
		@ID_CP
	END
	AND
	CAST(CP_CUSTOMER_ID as varchar) LIKE
	CASE WHEN @CP_CUSTOMER_ID IS NULL THEN
		'%'
	ELSE
		@CP_CUSTOMER_ID
	END