GO
/****** Object:  StoredProcedure [dbo].[USP_FETCH_VEHICLE_DETAILS]    Script Date: 9/11/2015 2:24:06 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
-- =============================================
-- Author:		Thomas Won Nyheim (TWN)
-- Create date: 2015/5/11
-- Modified: 2015/5/12 TWN - Added single row query validator
-- Modified: 2015/9/11 TWN - Added multiple columns for fetchVehicleDetails
-- Description:	Fetches vehicles for dashboard search
-- =============================================
CREATE PROCEDURE [dbo].[USP_VEHICLE_SEARCH]

@ID_SEARCH VARCHAR(255)
AS
DECLARE @string as varchar(255) = @ID_SEARCH
DECLARE @string_cut as varchar (255) = REPLACE(@string, ' ', ';')
DECLARE @parsed_query as nvarchar(2000)
DECLARE @i int = 1
DECLARE @query_col as nvarchar(1000) = 'ISNULL(VEH_REG_NO,'''') + ISNULL(VEH_VIN,'''') + ISNULL(VEH_INTERN_NO,'''') + ISNULL(VEH_VIN,'''') + ISNULL(ID_MAKE_VEH,'''') + ISNULL(VEH_TYPE,'''') + ISNULL(CUST_NAME,'''')' -- SEARCHABLE COLUMNS
SELECT * INTO #tmp_patterns FROM dbo.ParseValues(@string_cut, ';')


DECLARE @stringCount as int = (SELECT COUNT(*) FROM #tmp_patterns)

SELECT TOP 0
	TMV.ID_VEH_SEQ,TMV.VEH_REG_NO,TMV.VEH_INTERN_NO,TMV.VEH_VIN,TMV.ID_MAKE_VEH,TMV.ID_MODEL_VEH,TMV.VEH_TYPE,TMV.DT_VEH_ERGN,TMV.VEH_MILEAGE,TMV.DT_VEH_MIL_REGN,TMV.VEH_HRS,
	TMV.DT_VEH_HRS_ERGN,TMV.ID_MODEL_RP,TMV.VEH_MDL_YEAR,TMV.ID_GROUP_VEH,TMV.ID_CUSTOMER_VEH,TMV.VEH_DRIVER,TMV.VEH_MOBILE,TMV.VEH_PHONE1,TMV.VEH_DRV_IDEMIAL,
	TMV.VEH_FLG_SERVICE_PLAN,TMV.VEH_FLG_ADDON,TMV.ID_SER_TYP,TMV.ID_ADDON_LOCDEPT,TMV.VEH_ANNOT,TMV.ID_VAT_CD,TMV.CERATED_BY,TMV.DT_CREATED,TMV.MODIFIED_BY,TMV.DT_MODIFIED,COST_PRICE,
	TMV.SELL_PRICE,TMV.VA_ACC_CODE,TMV.PICK,TMV.VAN_NUM,TMV.VEH_REFNO,TMV.VEH_NEW_USED,TMV.VEH_STATUS,TMV.VEH_MODEL_TYPE,TMV.VEH_REGYEAR,TMV.VEH_REG_DATE_NO,TMV.VEH_LAST_REGDATE,
	TMV.VEH_DEREG_DATE,TMV.VEH_CATEGORY,TMV.VEH_MACHINE_W_HOURS,TMV.VEH_COLOR,TMV.VEH_WARRANTY_CODE,TMV.VEH_NET_WEIGHT,TMV.VEH_TOT_WEIGHT,TMV.VEH_PROJECT_NO,TMV.VEH_LAST_CONTACT_DATE,
	TMV.VEH_PRACTICAL_LOAD,TMV.VEH_MAX_ROOF_LOAD,TMV.VEH_EARLIER_REGNO_1,TMV.VEH_EARLIER_REGNO_2,TMV.VEH_EARLIER_REGNO_3,TMV.VEH_EARLIER_REGNO_4,TMV.VEH_NOTE, TMC.CUST_NAME
	INTO #tmp_res 
FROM 
	TBL_MAS_VEHICLE TMV 
	LEFT JOIN TBL_MAS_CUSTOMER TMC 
	ON TMC.ID_CUSTOMER = TMV.ID_CUSTOMER_VEH 

WHILE @i <= @stringCount
BEGIN
	DECLARE @value as varchar(150) = (SELECT Val FROM dbo.ParseValues(@string_cut, ';') WHERE ID = @i)
	INSERT INTO 
		#tmp_res 
	SELECT 
		TMV.ID_VEH_SEQ,TMV.VEH_REG_NO,TMV.VEH_INTERN_NO,TMV.VEH_VIN,TMV.ID_MAKE_VEH,TMV.ID_MODEL_VEH,TMV.VEH_TYPE,TMV.DT_VEH_ERGN,TMV.VEH_MILEAGE,TMV.DT_VEH_MIL_REGN,TMV.VEH_HRS,
		TMV.DT_VEH_HRS_ERGN,TMV.ID_MODEL_RP,TMV.VEH_MDL_YEAR,TMV.ID_GROUP_VEH,TMV.ID_CUSTOMER_VEH,TMV.VEH_DRIVER,TMV.VEH_MOBILE,TMV.VEH_PHONE1,TMV.VEH_DRV_IDEMIAL,
		TMV.VEH_FLG_SERVICE_PLAN,TMV.VEH_FLG_ADDON,TMV.ID_SER_TYP,TMV.ID_ADDON_LOCDEPT,TMV.VEH_ANNOT,TMV.ID_VAT_CD,TMV.CERATED_BY,TMV.DT_CREATED,TMV.MODIFIED_BY,TMV.DT_MODIFIED,COST_PRICE,
		TMV.SELL_PRICE,TMV.VA_ACC_CODE,TMV.PICK,TMV.VAN_NUM,TMV.VEH_REFNO,TMV.VEH_NEW_USED,TMV.VEH_STATUS,TMV.VEH_MODEL_TYPE,TMV.VEH_REGYEAR,TMV.VEH_REG_DATE_NO,TMV.VEH_LAST_REGDATE,
		TMV.VEH_DEREG_DATE,TMV.VEH_CATEGORY,TMV.VEH_MACHINE_W_HOURS,TMV.VEH_COLOR,TMV.VEH_WARRANTY_CODE,TMV.VEH_NET_WEIGHT,TMV.VEH_TOT_WEIGHT,TMV.VEH_PROJECT_NO,TMV.VEH_LAST_CONTACT_DATE,
		TMV.VEH_PRACTICAL_LOAD,TMV.VEH_MAX_ROOF_LOAD,TMV.VEH_EARLIER_REGNO_1,TMV.VEH_EARLIER_REGNO_2,TMV.VEH_EARLIER_REGNO_3,TMV.VEH_EARLIER_REGNO_4,TMV.VEH_NOTE, TMC.CUST_NAME
	FROM 
		TBL_MAS_VEHICLE TMV 
		LEFT JOIN TBL_MAS_CUSTOMER TMC 
		ON TMC.ID_CUSTOMER = TMV.ID_CUSTOMER_VEH 
	WHERE 
		ISNULL(TMV.VEH_REG_NO,'') + ISNULL(TMV.VEH_VIN,'') + ISNULL(TMV.VEH_INTERN_NO,'') + ISNULL(TMV.VEH_VIN,'') + ISNULL(TMV.ID_MAKE_VEH,'') + ISNULL(TMV.VEH_TYPE,'') + ISNULL(TMC.CUST_NAME,'') LIKE '%' + @value + '%'
	IF @i = 1 
		SET @parsed_query = CONCAT(@parsed_query,'SELECT DISTINCT * FROM #tmp_res WHERE ', @query_col, ' LIKE ''%', @value, '%'' ') -- ADDS BEGINNING STATEMENT
	ELSE
		SET @parsed_query = CONCAT(@parsed_query, 'AND ', @query_col, ' LIKE ''%', @value, '%'' ') -- ALL FOLLOWING STATEMENTS POST SELECT AND WHERE

	SET @i = @i + 1
END

-- SELECT * FROM #tmp_res ORDER BY VEH_REG_NO ASC -- Matches all results from all queries
EXECUTE sp_executesql @parsed_query -- Parsed dynamic query, must match all search queries in single row

DROP TABLE #tmp_res
DROP TABLE #tmp_patterns