USE [CARSDEV]
GO
/****** Object:  StoredProcedure [dbo].[USP_GDPR_INSERT]    Script Date: 01.06.2022 10:49:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


ALTER PROCEDURE [dbo].[USP_GDPR_INSERT] 
(
	@ID_CUSTOMER			varchar(10)		= NULL, -- IF NULL CREATE NEW 
    @MANUAL_SMS				bit				= 0,	
    @MANUAL_MAIL			bit				= 0,
    @PKK_SMS				bit				= 0,
    @PKK_MAIL				bit				= 0,
    @SERVICE_SMS			bit				= 0,
    @SERVICE_MAIL			bit				= 0,
	@BARGAIN_SMS			bit				= 0,
    @BARGAIN_MAIL			bit				= 0,
	@XTRACHECK_SMS			bit				= 0,
    @XTRACHECK_MAIL			bit				= 0,
	@REMINDER_SMS			bit				= 0,
    @REMINDER_MAIL			bit				= 0,
	@INFO_SMS				bit				= 0,
    @INFO_MAIL				bit				= 0,
	@FOLLOWUP_SMS			bit				= 0,
    @FOLLOWUP_MAIL			bit				= 0,
	@MARKETING_SMS			bit				= 0,
    @MARKETING_MAIL			bit				= 0,
	@RESPONSE_DATE			varchar(20)				= NULL,
    @CREATED_BY				varchar(20)		, -- Required
    @MODIFIED_BY			varchar(20)		, -- Required   
	@RESPONSE_ID			varchar(200)	,
	@RETVAL					varchar(10) OUTPUT
	 
)

AS
BEGIN

DECLARE @DT_CREATED DATETIME = getdate()
DECLARE @DT_MODIFIED DATETIME = getdate()
DECLARE @VALIDATE BIT = 1

IF @RESPONSE_DATE IS NULL OR @RESPONSE_DATE = ''
BEGIN
	SET @RESPONSE_DATE = GETDATE()
END
IF @ID_CUSTOMER IS NULL OR @ID_CUSTOMER = ''
BEGIN
	SET @VALIDATE = 0
END

-- Insert Statement if customer does not exist
IF NOT EXISTS (SELECT * FROM TBL_MAS_CUSTOMER_GDPR WHERE CUST_NO = @ID_CUSTOMER) AND @VALIDATE = 1 AND LEN(@ID_CUSTOMER) > 0
BEGIN
	INSERT INTO [dbo].[TBL_MAS_CUSTOMER_GDPR]
				 ([CUST_NO]
           ,[MANUAL_SMS]
           ,[MANUAL_MAIL]
           ,[PKK_SMS]
           ,[PKK_MAIL]
           ,[SERVICE_SMS]
           ,[SERVICE_MAIL]
           ,[BARGAIN_SMS]
           ,[BARGAIN_MAIL]
           ,[XTRACHECK_SMS]
           ,[XTRACHECK_MAIL]
           ,[REMINDER_SMS]
           ,[REMINDER_MAIL]
           ,[INFO_SMS]
           ,[INFO_MAIL]
           ,[FOLLOWUP_SMS]
           ,[FOLLOWUP_MAIL]
           ,[MARKETING_SMS]
           ,[MARKETING_MAIL]
           ,[DT_RESPONSE]
           ,[DT_CREATED]
           ,[DT_CREATED_BY]
		   ,[RESPONSE_ID]
		   )
			VALUES
				(@ID_CUSTOMER,
				@MANUAL_SMS,
				@MANUAL_MAIL,
				@PKK_SMS,
				@PKK_MAIL,
				@SERVICE_SMS,
				@SERVICE_MAIL,
				@BARGAIN_SMS,
				@BARGAIN_MAIL,
				@XTRACHECK_SMS,
				@XTRACHECK_MAIL,
				@REMINDER_SMS,
				@REMINDER_MAIL,
				@INFO_SMS,
				@INFO_MAIL,
				@FOLLOWUP_SMS,
				@FOLLOWUP_MAIL,
				@MARKETING_SMS,
				@MARKETING_MAIL,
				'',
				@DT_CREATED,
				@CREATED_BY,
				@RESPONSE_ID
			)
		SET @RETVAL = 'INSFLG'
END
ELSE IF EXISTS (SELECT * FROM TBL_MAS_CUSTOMER_GDPR WHERE CUST_NO = @ID_CUSTOMER) AND @VALIDATE = 1
BEGIN
	UPDATE [dbo].[TBL_MAS_CUSTOMER_GDPR]
   SET 
      [MANUAL_SMS] = @MANUAL_SMS
      ,[MANUAL_MAIL] = @MANUAL_MAIL
      ,[PKK_SMS] = @PKK_SMS
      ,[PKK_MAIL] = @PKK_MAIL
      ,[SERVICE_SMS] = @SERVICE_SMS
      ,[SERVICE_MAIL] = @SERVICE_MAIL
      ,[BARGAIN_SMS] = @BARGAIN_SMS
      ,[BARGAIN_MAIL] = @BARGAIN_MAIL
      ,[XTRACHECK_SMS] = @XTRACHECK_SMS
      ,[XTRACHECK_MAIL] = @XTRACHECK_MAIL
      ,[REMINDER_SMS] = @REMINDER_SMS
      ,[REMINDER_MAIL] = @REMINDER_MAIL
      ,[INFO_SMS] = @INFO_SMS
      ,[INFO_MAIL] = @INFO_MAIL
      ,[FOLLOWUP_SMS] = @FOLLOWUP_SMS
      ,[FOLLOWUP_MAIL] = @FOLLOWUP_MAIL
      ,[MARKETING_SMS] = @MARKETING_SMS
      ,[MARKETING_MAIL] = @MARKETING_MAIL
      ,[DT_RESPONSE] = @RESPONSE_DATE
      ,[DT_MODIFIED] = @DT_MODIFIED
      ,[DT_MODIFIED_BY] = @MODIFIED_BY
	  
	WHERE 
		CUST_NO = @ID_CUSTOMER
	SET @RETVAL = 'UPDFLG'
	END
END
IF @VALIDATE = 0
BEGIN
 SET @RETVAL = 'ERRFLG'
END

PRINT @RETVAL