USE [CARSDEV]
GO
/****** Object:  StoredProcedure [dbo].[USP_SPR_PO_FETCH_BACKORDER_ITEMS]    Script Date: 18.03.2022 12:26:51 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


CREATE PROCEDURE [dbo].[USP_RPT_PO_BACKORDER_ITEMS]

AS
BEGIN

SELECT JD.[ID_WOITEM_SEQ]
,JD.[ID_WODET_SEQ_JOB]
,JD.[ID_MAKE_JOB]
 ,(SELECT CATG_DESC FROM TBL_MAS_ITEM_CATG WHERE ID_ITEM_CATG = JD.[ID_ITEM_CATG_JOB] ) AS ITEM_CATG_DESC
	   ,JD.[ID_ITEM_JOB] 
	   ,JD.[ITEM_DESC]
      ,JD.[ID_WO_PREFIX]+JD.[ID_WO_NO] AS ID_WO_NO
       ,JD.[JOBI_ORDER_QTY]
      ,JD.[JOBI_DELIVER_QTY]
      ,JD.[JOBI_BO_QTY]            
      ,(SELECT CATG_DESC FROM TBL_MAS_ITEM_CATG WHERE ID_ITEM_CATG = JD.[ID_ITEM_CATG_JOB] ) AS ITEM_CATG_DESC
	  ,(SELECT ID_ITEM_CATG FROM TBL_MAS_ITEM_CATG WHERE ID_ITEM_CATG = JD.[ID_ITEM_CATG_JOB] ) AS ID_ITEM_CATG
     ,JD.[ID_WAREHOUSE] 
	  ,JD.[ID_ITEM_CATG_JOB] 
        ,(SELECT ISNULL(ITEM_AVAIL_QTY, 0 ) FROM TBL_MAS_ITEM_MASTER IM WHERE IM.ID_ITEM = JD.ID_ITEM_JOB AND IM.ID_MAKE = JD.ID_MAKE_JOB AND IM.ID_ITEM_CATG = ID_ITEM_CATG) AS ITEM_AVAIL_QTY
	  ,(SELECT COALESCE(SUM(POI.REMAINING_QTY),0) FROM TBL_SPR_PO_ITEM POI WHERE POI.ID_ITEM = JD.ID_ITEM_JOB ) AS IN_DELIVERY
	  ,(SELECT COST_PRICE1 FROM TBL_MAS_ITEM_MASTER IM WHERE IM.ID_ITEM = JD.ID_ITEM_JOB AND IM.ID_MAKE = JD.ID_MAKE_JOB AND IM.ID_ITEM_CATG = ID_ITEM_CATG) AS COST_PRICE1
	  ,(SELECT ITEM_PRICE FROM TBL_MAS_ITEM_MASTER IM WHERE IM.ID_ITEM = JD.ID_ITEM_JOB AND IM.ID_MAKE = JD.ID_MAKE_JOB AND IM.ID_ITEM_CATG = ID_ITEM_CATG) AS ITEM_PRICE
	  ,(SELECT NET_PRICE FROM TBL_MAS_ITEM_MASTER IM WHERE IM.ID_ITEM = JD.ID_ITEM_JOB AND IM.ID_MAKE = JD.ID_MAKE_JOB AND IM.ID_ITEM_CATG = ID_ITEM_CATG) AS NET_PRICE
	  ,(SELECT BASIC_PRICE FROM TBL_MAS_ITEM_MASTER IM WHERE IM.ID_ITEM = JD.ID_ITEM_JOB AND IM.ID_MAKE = JD.ID_MAKE_JOB AND IM.ID_ITEM_CATG = ID_ITEM_CATG) AS BASIC_PRICE
      ,JD.[ID_MAKE]
           
      
	  ,JD.[TEXT]
	 
	  

	  /*, (
		case @THE_PRICETYPE
		when 'CostPrice1' then (SELECT COST_PRICE1 FROM TBL_MAS_ITEM_MASTER	WHERE ID_ITEM = JD.ID_ITEM_JOB)
		when 'CostPrice2' then (SELECT COST_PRICE2 FROM TBL_MAS_ITEM_MASTER	WHERE ID_ITEM = JD.ID_ITEM_JOB)
		end

	   )*/
	   
		 		 	     
  FROM [CARSDEV].[dbo].[TBL_WO_JOB_DETAIL] JD
  inner join TBL_WO_DETAIL WD ON JD.ID_WODET_SEQ_JOB = WD.ID_WODET_SEQ 
  
  where 
  
  JOBI_BO_QTY > 0
  AND
  WD.JOB_STATUS <> 'INV'
  AND 
  JD.ID_WOITEM_SEQ not IN (SELECT ID_WOITEM_SEQ FROM TBL_SPR_PO_ITEM WHERE ID_WOITEM_SEQ IS NOT NULL)
  




  

 
END


