USE [CARSDEV]
GO
/****** Object:  StoredProcedure [dbo].[USP_SPR_COUNTING_FETCH_ITEMS]    Script Date: 15.03.2022 16:01:12 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [dbo].[USP_SPR_COUNTING_FETCH_ITEMS]
(
	
	@warehouseId int,
	@supplier varchar(30),
	@user varchar(20),
	@catgFrom varchar(30) = NULL,
	@catgTo varchar(30) = NULL,
	@spareFrom varchar(30) = NULL,
	@spareTo varchar(30) = NULL,
	@locationFrom varchar(30) = NULL,
	@locationTo varchar(30) = NULL,
	@dateFrom varchar(30) = NULL,
	@dateTo varchar(30) = NULL,
	@stock varchar(10),
	@nolocation varchar(10),
	@sortBy int = 0
)
AS
BEGIN
DECLARE @MAINQRY AS NVARCHAR(MAX)
DECLARE @CQRY AS NVARCHAR(MAX) = ''
--DECLARE @THE_PRICETYPE varchar(60)

--SELECT @THE_PRICETYPE = PRICETYPE 
--FROM TBL_SPR_SUPPLIERCONFIG
--WHERE ((SUPP_CURRENTNO LIKE @SUPP_CURRENTNO) AND SUPP_ORDERTYPE LIKE @ID_ORDERTYPE)
--print(@THE_PRICETYPE)

SET @MAINQRY = N'SELECT IM.ID_ITEM
	, IM.ITEM_DESC
	, (SELECT CATG_DESC FROM TBL_MAS_ITEM_CATG IC WHERE IC.ID_ITEM_CATG = IM.ID_ITEM_CATG) AS ITEM_CATG_DESC 
	,IM.ID_WH_ITEM
	,IM.ID_ITEM_CATG
	,IM.ITEM_AVAIL_QTY AS STOCKBEFORECOUNT
	,ISNULL(IM.LOCATION, '''') as LOCATION
	,(SELECT ISNULL((SELECT TOP (1) CO.LAST_COUNTED_DATE FROM TBL_SPR_COUNTING CO WHERE CO.ID_ITEM = IM.ID_ITEM AND CO.ID_WH = IM.ID_WH_ITEM and co.SUPP_CURRENTNO = im.SUPP_CURRENTNO ORDER BY LAST_COUNTED_DATE DESC), NULL)) AS LAST_COUNTED_DATE
	,(SELECT ISNULL((SELECT TOP (1) COALESCE(CO.CREATED_BY, '''') FROM TBL_SPR_COUNTING CO WHERE CO.ID_ITEM = IM.ID_ITEM AND CO.ID_WH = IM.ID_WH_ITEM and co.SUPP_CURRENTNO = im.SUPP_CURRENTNO ORDER BY DT_CREATED DESC), '''')) AS CREATED_BY
	,IM.SUPP_CURRENTNO
	,IM.AVG_PRICE
	,IM.ITEM_PRICE
	,IM.COST_PRICE1
	FROM TBL_MAS_ITEM_MASTER IM
	WHERE IM.ID_WH_ITEM ='+ CONVERT(VARCHAR(10),@warehouseId)+' AND NOT IM.ID_ITEM IN (SELECT ID_ITEM FROM TBL_SPR_COUNTING WHERE CLOSED = 0)'

	IF @supplier <> ''
		SET @CQRY = ' AND (IM.SUPP_CURRENTNO = ''' + @supplier + ''')'

	IF @sparefrom <> '' AND @spareto <> '' 
		SET @CQRY = @CQRY + ' AND (IM.ID_ITEM between ''' + @sparefrom + '%'' AND ''' + @spareTo + '%'')'
						                                        

	IF @locationFrom <> '' AND @locationTo <> ''
		SET @CQRY = @CQRY + ' AND (IM.LOCATION between ''' + @locationFrom + '%'' AND ''' + @locationTo + '%'')'


	IF @stock = 1
		SET @CQRY = @CQRY + ' AND IM.ITEM_AVAIL_QTY > 0'
	
	IF @nolocation = 1
		SET @CQRY = @CQRY + ' AND IM.LOCATION IS NULL OR IM.LOCATION = '''''
		
	
	IF @sortBy = '1' 
		SET @CQRY = @CQRY +  ' ORDER BY IM.ID_ITEM ASC'

	ELSE IF @sortBy = '2' 
		SET @CQRY = @CQRY +  ' ORDER BY IM.ITEM_DESC ASC'

	ELSE IF @sortBy = '3' 
		SET @CQRY = @CQRY +  ' ORDER BY IM.LOCATION ASC'

	IF @CQRY <> ''
		SET @MAINQRY = @MAINQRY + @CQRY
		print @MAINQRY

	EXEC (@MAINQRY) 	

  

 
END


 --SET @MAINQRY = N'SELECT IM.ID_ITEM
	--, IM.ITEM_DESC
	--, (SELECT CATG_DESC FROM TBL_MAS_ITEM_CATG IC WHERE IC.ID_ITEM_CATG = IM.ID_ITEM_CATG) AS ITEM_CATG_DESC 
	--,IM.ID_WH_ITEM
	--,IM.ID_ITEM_CATG
	--,IM.ITEM_AVAIL_QTY AS STOCKBEFORECOUNT
	--,ISNULL(IM.LOCATION, '') AS LOCATION
	--,(SELECT ISNULL((SELECT TOP (1) CO.DT_CREATED FROM TBL_SPR_COUNTING CO WHERE CO.ID_ITEM = IM.ID_ITEM AND CO.ID_WH = IM.ID_WH_ITEM and co.SUPP_CURRENTNO = im.SUPP_CURRENTNO ORDER BY DT_CREATED DESC), '')) AS DT_CREATED
	--,(SELECT ISNULL((SELECT TOP (1) COALESCE(CO.CREATED_BY, '') FROM TBL_SPR_COUNTING CO WHERE CO.ID_ITEM = IM.ID_ITEM AND CO.ID_WH = IM.ID_WH_ITEM and co.SUPP_CURRENTNO = im.SUPP_CURRENTNO ORDER BY DT_CREATED DESC), @user)) AS CREATED_BY
	--,IM.SUPP_CURRENTNO
	--,IM.AVG_PRICE
	--,IM.ITEM_PRICE
	--,IM.COST_PRICE1
	--FROM TBL_MAS_ITEM_MASTER IM
	--WHERE IM.ID_WH_ITEM = '+CONVERT(int, @warehouseId)-- and IM.SUPP_CURRENTNO = @supplier

	--IF @supplier <> ''  
	--	SET @CQRY = ' and IM.SUPP_CURRENTNO = '+ @supplier
	-- -- ,(SELECT ISNULL(ITEM_AVAIL_QTY, 0 ) FROM TBL_MAS_ITEM_MASTER IM WHERE IM.ID_ITEM = JD.ID_ITEM_JOB AND IM.ID_MAKE = @SUPP_CURRENTNO AND IM.ID_ITEM_CATG = ID_ITEM_CATG) AS ITEM_AVAIL_QTY
	-- -- ,(SELECT COALESCE(SUM(POI.REMAINING_QTY),0) FROM TBL_SPR_PO_ITEM POI WHERE POI.ID_ITEM = JD.ID_ITEM_JOB ) AS IN_DELIVERY
	
	--  /*, (
	--	case @THE_PRICETYPE
	--	when 'CostPrice1' then (SELECT COST_PRICE1 FROM TBL_MAS_ITEM_MASTER	WHERE ID_ITEM = JD.ID_ITEM_JOB)
	--	when 'CostPrice2' then (SELECT COST_PRICE2 FROM TBL_MAS_ITEM_MASTER	WHERE ID_ITEM = JD.ID_ITEM_JOB)
	--	end

	--   )*/
	--    SET @MAINQRY = @MAINQRY + @CQRY
	--	EXEC (@MAINQRY) 		 	     
  

