USE [CARSDEV]
GO
/****** Object:  StoredProcedure [dbo].[USP_ITEM_FETCH]    Script Date: 15.02.2017 15.10.08 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

ALTER PROCEDURE [dbo].[USP_ITEM_FETCH] (
	@ID_ITEM_MAKE				VARCHAR(50) = NULL
	,@ID_ITEM_ID				VARCHAR(50) = NULL
	,@ID_ITEM_WH				VARCHAR(50) = NULL
	--,@RETVAL			VARCHAR(10) OUTPUT
)
AS

--DECLARE @ID_ITEM_MAKE VARCHAR(50) = 'VP'
--DECLARE @ID_ITEM_ID VARCHAR(50) = '1161648'
--DECLARE @ID_ITEM_WH VARCHAR(50) = 1
DECLARE @LCP DECIMAL = (SELECT LAST_COST_PRICE FROM TBL_MAS_ITEM_MASTER WHERE ID_MAKE = @ID_ITEM_MAKE AND ID_ITEM = @ID_ITEM_ID AND ID_WH_ITEM = @ID_ITEM_WH)
IF (@LCP IS NULL)
BEGIN
	UPDATE 
		TBL_MAS_ITEM_MASTER 
	SET 
		LAST_COST_PRICE = (SELECT TOP 1 COSTPRICE FROM TBL_SPR_INWARDREGISTER WHERE ID_MAKE = @ID_ITEM_MAKE AND ID_ITEM = @ID_ITEM_ID AND ID_WH_ITEM = @ID_ITEM_WH ORDER BY DT_INWARD ASC)
	WHERE 
		ID_MAKE = @ID_ITEM_MAKE AND ID_ITEM = @ID_ITEM_ID AND ID_WH_ITEM = @ID_ITEM_WH
END

SELECT 
	--##DETAILS
	IM.ID_ITEM
	,IM.ITEM_DESC
	,IM.ID_MAKE
	,IM.ITEM_DISC_CODE
	,IM.ITEM_DISC_CODE_BUY
	,IM.ID_SUPPLIER_ITEM
	,MS.SUP_Name
	,IM.LOCATION
	,IM.ALT_LOCATION
	,IM.ITEM_AVAIL_QTY
	,IM.ANNOTATION
	--##REPLACEMENTS
	,SR1.ID_LOCALSPAREPART AS PREVIOUS_ITEM_ID
	,SR2.ID_REPLACESPARE AS NEW_ITEM_ID
	-- ##PRICE
	,IM.BASIC_PRICE
	,IM.AVG_PRICE
	,IIF(IM.LAST_COST_PRICE is not NULL or IM.LAST_COST_PRICE > '0.00', IM.LAST_COST_PRICE, IM.COST_PRICE1) as LAST_COST_PRICE
	,IM.ITEM_PRICE
	,IM.COST_PRICE1
	-- ##PARAMETERS
	,IM.FLG_STOCKITEM
	,IM.FLG_VAT_INCL
	,IM.FLG_OBTAIN_SPARE
	,IM.FLG_OBSOLETE_SPARE
	,IM.FLG_BLOCK_AUTO_ORD
	,IM.FLG_AUTOADJUST_PRICE
	,IM.FLG_LABELS
	,IM.FLG_ALLOW_DISCOUNT
	,IM.FLG_SAVE_TO_NONSTOCK
	,IM.FLG_AUTO_ARRIVAL
	,IM.FLG_REPLACEMENT_PURCHASE
	,FLG_EFD
	,IM.DISCOUNT
	-- ##META
	,IM.DT_CREATED
	,IM.CREATED_BY
	,IM.DT_MODIFIED
	,IM.MODIFIED_BY
	,IM.ID_WH_ITEM
	,IM.TEXT
	-- ##ADVANCED TAB
	,IM.PACKAGE_QTY
	,IM.MIN_STOCK
	,IM.MAX_STOCK
	,IIF(IM.ID_UNIT_ITEM is NULL , 0, IM.ID_UNIT_ITEM) as ID_UNIT_ITEM
	,IM.LAST_BUY_PRICE
	,DT_LAST_BUY
	,IM.QTY_BO_SUPPLIER
	,IM.WEIGHT
	,IM.ENV_ID_ITEM
	,IM.ENV_ID_MAKE
	,IM.ENV_ID_WAREHOUSE
	,IM.ID_SPCATEGORY
	,IM.SUPP_CURRENTNO
	,MS.SUP_CURRENCY_CODE

FROM 
	TBL_MAS_ITEM_MASTER IM
	INNER JOIN
	TBL_MAS_SUPPLIER MS -- FETCH SUPPLIER NAME FROM SUPPLIER ID
	ON
		IM.ID_SUPPLIER_ITEM = MS.ID_SUPPLIER
	LEFT JOIN 
	TBL_SPR_REPLACEMENT SR1
	ON
		IM.ID_ITEM = SR1.ID_REPLACESPARE
		AND IM.ID_MAKE = SR1.ID_MAKE_REPLACE 
		--AND IM.ID_WH_ITEM = SR1.ID_WH_ITEM
	LEFT JOIN
	TBL_SPR_REPLACEMENT SR2
	ON
		IM.ID_ITEM = SR2.ID_LOCALSPAREPART
		AND IM.ID_MAKE = SR2.ID_MAKE_LOCAL 
		--AND IM.ID_WH_ITEM = SR2.ID_WH_ITEM
WHERE 
	ID_MAKE = @ID_ITEM_MAKE 
	AND ID_ITEM = @ID_ITEM_ID 
	AND ID_WH_ITEM = @ID_ITEM_WH


	--SELECT * FROM TBL_MAS_ITEM_MASTER
	--SELECT * FROM TBL_SPR_REPLACEMENT


--SELECT TOP(1)
--IR.IRNUMBER, 
--IR.ID_ITEM, 
--IR.DELIVEREDQTY, 
--IR.DT_CREATED, 
--IR.COSTPRICE,
--(SELECT TOP(1) FROM TBL_SPR_PURCHASEORDER WHERE ID_ITEM = @ID_ITEM_ID  and ID_MAKE = @ID_ITEM_MAKE and ID_WH_ITEM = @ID_ITEM_WH)
--FROM TBL_SPR_INWARDREGISTER IR
--WHERE ID_ITEM = @ID_ITEM_ID  and ID_MAKE = @ID_ITEM_MAKE and ID_WH_ITEM = @ID_ITEM_WH
--ORDER BY DT_INWARD DESC


IF OBJECT_ID('tempdb..#temp_spareadvanced')IS NOT NULL DROP TABLE #temp_spareadvanced
CREATE TABLE #temp_spareadvanced (
	PO_NO varchar(50),
	PO_QTY varchar(25),
	PO_DT_CREATED DateTime,
	PO_DT_EXPDLVDATE DateTime,
	PO_ANNOTATION varchar(100),
	IR_NO varchar(50),
	IR_QTY varchar(50),
	COUNTING_DATE DateTime,
	COUNTING_CREATED_BY varchar(30),
	DT_LAST_SOLD datetime,
	DT_LAST_BO datetime,
	TOTAL_BO_QTY decimal(15,2),
	TOTAL_ORDER_BO_QTY int,
	TOTAL_BARGAIN_BO_QTY decimal(15,2))

INSERT INTO
	#temp_spareadvanced (
	PO_NO,
	PO_QTY,
	PO_DT_CREATED,
	PO_DT_EXPDLVDATE,
	PO_ANNOTATION)

SELECT TOP(1)
	PO.PONUMBER,
	REPLACE(PO.ORDERQTY, '.', ','),
	DT_CREATED,
	DT_EXPDLVDATE,
	ANNOTATION
FROM 
	bootcamp.dbo.TBL_SPR_PURCHASEORDER PO 
WHERE 
	ID_ITEM = @ID_ITEM_ID AND ID_MAKE = @ID_ITEM_MAKE AND ID_WAREHOUSE=@ID_ITEM_WH
	ORDER BY DT_CREATED DESC
	

UPDATE #temp_spareadvanced
SET	IR_NO = IR.IRNUMBER,
	IR_QTY = REPLACE(IR.DELIVEREDQTY, '.', ',')
FROM 
(SELECT TOP(1)
IRNUMBER, 
DELIVEREDQTY 
FROM TBL_SPR_INWARDREGISTER 
WHERE ID_ITEM = @ID_ITEM_ID  and ID_MAKE = @ID_ITEM_MAKE and ID_WH_ITEM = @ID_ITEM_WH 
ORDER BY DT_INWARD DESC) AS IR

UPDATE #temp_spareadvanced 
SET	COUNTING_DATE = COUNT.COUNTING_DATE,
	COUNTING_CREATED_BY = COUNT.CREATED_BY
FROM (SELECT TOP(1) 
COUNTING_DATE,
CREATED_BY
FROM TBL_SPR_COUNTING
WHERE ID_ITEM = @ID_ITEM_ID  and ID_MAKE = @ID_ITEM_MAKE and ID_WH = @ID_ITEM_WH
ORDER BY DT_CREATED DESC) AS COUNT

UPDATE #temp_spareadvanced 
SET	DT_LAST_SOLD = DLS.DT_CREATED
FROM (select top 1 DT_CREATED FROM BOOTCAMP.DBO.TBL_INV_DETAIL_LINES 
WHERE ID_ITEM_INVL = @ID_ITEM_ID  and ID_MAKE = @ID_ITEM_MAKE and ID_WAREHOUSE = @ID_ITEM_WH
ORDER BY DT_CREATED DESC) AS DLS

UPDATE #temp_spareadvanced 
SET	DT_LAST_BO = DLB.DT_CREATED
FROM (select top 1 DT_CREATED from BOOTCAMP.DBO.TBL_WO_JOB_DETAIL 
WHERE ID_ITEM_JOB = @ID_ITEM_ID and ID_MAKE_JOB = @ID_ITEM_MAKE and ID_WAREHOUSE = @ID_ITEM_WH and JOBI_BO_QTY > 0 
ORDER BY DT_CREATED desc) as DLB

UPDATE #temp_spareadvanced 
SET	TOTAL_BO_QTY = TBQ.BO_QTY
FROM (SELECT SUM(JOBI_BO_QTY) AS BO_QTY from BOOTCAMP.DBO.TBL_WO_JOB_DETAIL 
WHERE ID_ITEM_JOB = @ID_ITEM_ID and ID_MAKE_JOB = @ID_ITEM_MAKE and ID_WAREHOUSE = @ID_ITEM_WH and JOBI_BO_QTY > 0) as TBQ

UPDATE #temp_spareadvanced 
SET	TOTAL_ORDER_BO_QTY = TBOQ.TIMES_BO_QTY
FROM (select COUNT(JOBI_BO_QTY) AS TIMES_BO_QTY from BOOTCAMP.DBO.TBL_WO_JOB_DETAIL
WHERE ID_ITEM_JOB = @ID_ITEM_ID and ID_MAKE_JOB = @ID_ITEM_MAKE and ID_WAREHOUSE = @ID_ITEM_WH and JOBI_BO_QTY > 0) as TBOQ

UPDATE #temp_spareadvanced 
SET	TOTAL_BARGAIN_BO_QTY = TBBQ.TIMES_BARGAIN_BO_QTY
FROM (select COUNT(JOBI_BO_QTY) AS TIMES_BARGAIN_BO_QTY from BOOTCAMP.DBO.TBL_WO_JOB_DETAIL
WHERE ID_ITEM_JOB = @ID_ITEM_ID and ID_MAKE_JOB = @ID_ITEM_MAKE and ID_WAREHOUSE = @ID_ITEM_WH and JOBI_BO_QTY > 0 AND STATUS='BAR') as TBBQ


SELECT * FROM #temp_spareadvanced


