USE [CARSDEV]
GO
/****** Object:  StoredProcedure [dbo].[USP_TIRE_PACKAGE_FETCH_CUSTOMER_DETAIL]    Script Date: 03.12.2021 15:50:36 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



ALTER PROCEDURE [dbo].[USP_TIRE_PACKAGE_FETCH_CUSTOMER_DETAIL]
(
 @custNo as varchar(max),
 @Search as varchar(max)
)
AS

BEGIN

IF @custNo <> ''
SELECT ID_CUSTOMER, CUST_FIRST_NAME, CUST_MIDDLE_NAME, CUST_LAST_NAME, FLG_PRIVATE_COMP, CUST_PERM_ADD1, ID_CUST_PERM_ZIPCODE, (select ZIP_CITY from TBL_MAS_ZIPCODE where ID_CUST_PERM_ZIPCODE = ZIP_ZIPCODE ) AS CUST_PERM_PLACE, (Select CONTACT_VALUE from TBL_MAS_CUSTOMER_CONTACT WHERE CONTACT_CUSTOMER_ID = ID_CUSTOMER AND CONTACT_TYPE = 1 AND CONTACT_STANDARD = 1) AS CUST_PHONE_MOBILE, (Select CONTACT_VALUE from TBL_MAS_CUSTOMER_CONTACT WHERE CONTACT_CUSTOMER_ID = ID_CUSTOMER AND CONTACT_TYPE = 6 AND CONTACT_STANDARD = 1) AS CUST_MAIL_ADDRESS 
FROM TBL_MAS_CUSTOMER 
WHERE ID_CUSTOMER = @custNo

ELSE
SELECT distinct MC.ID_CUSTOMER, MC.CUST_FIRST_NAME, MC.CUST_MIDDLE_NAME, MC.CUST_LAST_NAME, MC.FLG_PRIVATE_COMP, MC.CUST_PERM_ADD1, MC.ID_CUST_PERM_ZIPCODE, (select ZIP_CITY from TBL_MAS_ZIPCODE where ID_CUST_PERM_ZIPCODE = ZIP_ZIPCODE ) AS CUST_PERM_PLACE, (Select CONTACT_VALUE from TBL_MAS_CUSTOMER_CONTACT WHERE CONTACT_CUSTOMER_ID = ID_CUSTOMER AND CONTACT_TYPE = 1 AND CONTACT_STANDARD = 1) AS CUST_PHONE_MOBILE, (Select CONTACT_VALUE from TBL_MAS_CUSTOMER_CONTACT WHERE CONTACT_CUSTOMER_ID = ID_CUSTOMER AND CONTACT_TYPE = 6 AND CONTACT_STANDARD = 1) AS CUST_MAIL_ADDRESS 
FROM TBL_MAS_CUSTOMER MC
LEFT JOIN TBL_MAS_CUSTOMER_CONTACT CC ON CC.CONTACT_CUSTOMER_ID = MC.ID_CUSTOMER 
WHERE MC.ID_CUSTOMER LIKE '%' + @Search + '%' OR MC.CUST_FIRST_NAME LIKE '%' + @Search + '%' OR MC.CUST_MIDDLE_NAME LIKE '%' + @Search + '%' OR MC.CUST_LAST_NAME LIKE '%' + @Search + '%' OR CC.CONTACT_VALUE LIKE '%' + @Search + '%' OR MC.CUST_PERM_ADD1 LIKE '%' + @Search + '%'

END
 

 
 


