GO
/****** Object:  StoredProcedure [dbo].[USP_ITEM_HISTORY]    Script Date: 12/12/2016 12:00:00 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


IF NOT EXISTS (
	SELECT * 
	FROM sys.objects 
	WHERE type = 'P' AND name = 'USP_ITEM_HISTORY'
	)
	BEGIN
		EXEC('CREATE PROCEDURE [dbo].[USP_ITEM_HISTORY] 
			  AS 
			  BEGIN 
				  SET NOCOUNT ON; 
			  END'
		)
	END

-- =============================================
-- Author:		Thomas Won Nyheim (TWN)
-- Create date: 2016/12/12
-- Description:	FETCHES THE SPARE PART REVENUE/ SALES HISTORY GROUPED BY YEAR AND MONTH
-- =============================================
GO

ALTER PROCEDURE [dbo].USP_ITEM_HISTORY (
	@ID_ITEM VARCHAR(100)
	,@ID_MAKE VARCHAR(10)
	,@ID_WAREHOUSE INT
)
AS
SELECT 
	YEAR(DT_CREATED) as M_YEAR
	,MONTH(DT_CREATED) as M_PERIOD
	,ISNULL(SUM(INVL_DELIVER_QTY),0.00) as M_TOTAL_SOLD_QTY
	,ISNULL(SUM(INVL_AVERAGECOST*INVL_DELIVER_QTY),0.00) as M_TOTAL_COST
	,ISNULL(SUM(INVL_AMOUNT),0.00) as M_TOTAL_GROSS
FROM 
	Bootcamp.dbo.TBL_INV_DETAIL_LINES 
WHERE 
	ID_ITEM_INVL = @ID_ITEM 
	AND ID_MAKE = @ID_MAKE 
	AND ID_WAREHOUSE = @ID_WAREHOUSE 
GROUP BY 
	MONTH(DT_CREATED),
	YEAR(DT_CREATED)
ORDER BY 
	YEAR(DT_CREATED),
	MONTH(DT_CREATED) 

SELECT 
	YEAR(DT_CREATED) as M_YEAR
	,'total' as M_PERIOD
	,ISNULL(SUM(INVL_DELIVER_QTY),0.00) as M_TOTAL_SOLD_QTY
	,ISNULL(SUM(INVL_AVERAGECOST*INVL_DELIVER_QTY),0.00) as M_TOTAL_COST
	,ISNULL(SUM(INVL_AMOUNT),0.00) as M_TOTAL_GROSS
FROM 
	Bootcamp.dbo.TBL_INV_DETAIL_LINES 
WHERE 
	ID_ITEM_INVL = @ID_ITEM 
	AND ID_MAKE = @ID_MAKE 
	AND ID_WAREHOUSE = @ID_WAREHOUSE 
GROUP BY 
	YEAR(DT_CREATED)