USE [CARSDEV]
GO
/****** Object:  StoredProcedure [dbo].[USP_TIRE_PACKAGE_NO_CLOSE]    Script Date: 07.12.2021 09:07:28 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO


  
CREATE PROCEDURE [dbo].[USP_TIRE_PACKAGE_DELETE]  
(  
	@TIREPACKAGENO VARCHAR(50),
	@USER VARCHAR(50), 	/*CURRENT USER WHO CREATES*/
	@CLOSED BIT
) 
AS  
  
BEGIN  
		
	IF(EXISTS(SELECT * FROM TBL_TIRE_ORDER_PACKAGE WHERE [tirePackageNo] = @TIREPACKAGENO and isFinished = 0))

	BEGIN
	DELETE FROM TBL_TIRE_PACKAGE_DEPTH
	WHERE TIRE_PACKAGE_NO = @TIREPACKAGENO and CLOSED = 0
	END
	DELETE FROM TBL_TIRE_ORDER_PACKAGE
	WHERE [tirePackageNo] = @TIREPACKAGENO and isFinished = 0
	
	--BEGIN
	--	UPDATE TBL_TIRE_PACKAGE_DEPTH
	--	SET CLOSED = 1
	--	WHERE TIRE_PACKAGE_NO = @packageNo AND CLOSED = 0
	--END
END