Public Class MechanicConfigSettingBO
	Public Property MechanicId() As String
	Public Property MechanicName() As String
	Public Property ActiveMek() As Integer
	Public Property PassiveMek() As Integer
	Public Property FlexTime() As Integer
	Public Property AdministrationMek() As Integer
	Public Property StandardFromTime() As String
	Public Property MondayFromTime() As String
	Public Property TuesdayFromTime() As String
	Public Property WednesdayFromTime() As String
	Public Property ThursdayFromTime() As String
	Public Property FridayFromTime() As String
	Public Property SaturdayFromTime() As String
	Public Property SundayFromTime() As String
	Public Property LunchFromTime() As String
	Public Property AltStandardFromTime() As String
	Public Property AltMondayFromTime() As String
	Public Property AltTuesdayFromTime() As String
	Public Property AltWednesdayFromTime() As String
	Public Property AltThursdayFromTime() As String
	Public Property AltFridayFromTime() As String
	Public Property AltSaturdayFromTime() As String
	Public Property AltSundayFromTime() As String
	Public Property AltLunchFromTime() As String

	Public Property StandardToTime() As String
	Public Property MondayToTime() As String
	Public Property TuesdayToTime() As String
	Public Property WednesdayToTime() As String
	Public Property ThursdayToTime() As String
	Public Property FridayToTime() As String
	Public Property SaturdayToTime() As String
	Public Property SundayToTime() As String
	Public Property LunchToTime() As String
	Public Property AltStandardToTime() As String
	Public Property AltMondayToTime() As String
	Public Property AltTuesdayToTime() As String
	Public Property AltWednesdayToTime() As String
	Public Property AltThursdayToTime() As String
	Public Property AltFridayToTime() As String
	Public Property AltSaturdayToTime() As String
	Public Property AltSundayToTime() As String
	Public Property AltLunchToTime() As String
	Public Property DateFrom() As DateTime
	Public Property CreatedBy() As String
	Public Property DtCreated() As DateTime
	Public Property ModifiedBy() As String
    Public Property DtModified() As DateTime
    Public Property MechanicGroupId As Integer
    Public Property MechanicGroupName As String
    Public Property MechanicGroupIds As String
End Class
