Public Class TirePackageBO
    Public Property PackageNo As String
    Public Property refNo As String
    Public Property regNo As String
    Public Property make As String
    Public Property model As String
    Public Property custNo As String
    Public Property custName As String
    Public Property tirePackageNo As String
    Public Property qtyTire As String
    Public Property tireDimFront As String
    Public Property tireDimBack As String
    Public Property location As String
    Public Property tireTypeVal As String
    Public Property tireTypeDesc As String
    Public Property tireSpikesVal As String
    Public Property tireSpikesDesc As String
    Public Property tireRimVal As String
    Public Property tireRimDesc As String
    Public Property tireBrandVal As String
    Public Property tireBrandDesc As String
    Public Property tireQualityVal As String
    Public Property tireQualityDesc As String
    Public Property tireDepthVal As String
    Public Property tireDepthDesc As String
    Public Property tireAxleNoVal As String
    Public Property tireAxleNoDesc As String
    Public Property regDate As String
    Public Property outDate As String
    Public Property tireBolts As String
    Public Property tireCap As String
    Public Property tireAnnot As String
    Public Property custfName As String
    Public Property custmName As String
    Public Property custlName As String
    Public Property cust_add1 As String
    Public Property cust_zipcode As String
    Public Property cust_place As String
    Public Property custmobile As String
    Public Property custmail As String
    Public Property vehicle_group As String
    Public Property isFinished As String
    Public Property tirePackageVal As String
    Public Property flg_private_comp As String
    Public Property id_customer As String

    Public Property tireDepth1L As String
    Public Property tireDepth2L As String
    Public Property tireDepth2L2 As String
    Public Property tireDepth1R As String
    Public Property tireDepth2R As String
    Public Property tireDepth2R2 As String
    Public Property tireDepth3R As String
    Public Property tireDepth3R2 As String
    Public Property tireDepth4R As String
    Public Property tireDepth4R2 As String
    Public Property tireDepth5R As String
    Public Property tireDepth5R2 As String
    Public Property tireDepth6R As String
    Public Property tireDepth6R2 As String
    Public Property tireDepth3L As String
    Public Property tireDepth3L2 As String
    Public Property tireDepth4L As String
    Public Property tireDepth4L2 As String
    Public Property tireDepth5L As String
    Public Property tireDepth5L2 As String
    Public Property tireDepth6L As String
    Public Property tireDepth6L2 As String
    Public Property exist As String
    Public Property tireSeqNumber As String
End Class
