Public Class XtraCheckBO

    Public Property REFNR As String
    Public Property REGISTRATIONNR As String
    Public Property MOTOROIL As String
    Public Property MOTOROIL_ANNOT As String
    Public Property MOTOROIL_SMS As String
    Public Property FREEZE_LEVEL As String
    Public Property FREEZE_LEVEL_ANNOT As String
    Public Property FREEZE_LEVEL_SMS As String
    Public Property FREEZE_POINT As String
    Public Property FREEZE_POINT_ANNOT As String
    Public Property FREEZE_POINT_SMS As String
    Public Property BRAKEFLUID As String
    Public Property BRAKEFLUID_ANNOT As String
    Public Property BRAKEFLUID_SMS As String
    Public Property BATTERY As String
    Public Property BATTERY_ANNOT As String
    Public Property BATTERY_SMS As String
    Public Property WINDSCREEN_WIPER_FRONT As String
    Public Property WINDSCREEN_WIPER_FRONT_ANNOT As String
    Public Property WINDSCREEN_WIPER_FRONT_SMS As String
    Public Property WINDSCREEN_WIPER_REAR As String
    Public Property WINDSCREEN_WIPER_REAR_ANNOT As String
    Public Property WINDSCREEN_WIPER_REAR_SMS As String
    Public Property LIGHT_BULB_FRONT As String
    Public Property LIGHT_BULB_FRONT_ANNOT As String
    Public Property LIGHT_BULB_FRONT_SMS As String
    Public Property LIGHT_BULB_REAR As String
    Public Property LIGHT_BULB_REAR_ANNOT As String
    Public Property LIGHT_BULB_REAR_SMS As String
    Public Property SHOCK_ABSORBER_FRONT As String
    Public Property SHOCK_ABSORBER_FRONT_ANNOT As String
    Public Property SHOCK_ABSORBER_FRONT_SMS As String
    Public Property SHOCK_ABSORBER_REAR As String
    Public Property SHOCK_ABSORBER_REAR_ANNOT As String
    Public Property TIRE_FRONT As String
    Public Property TIRE_FRONT_ANNOT As String
    Public Property TIRE_FRONT_SMS As String
    Public Property TIRE_REAR As String
    Public Property TIRE_REAR_ANNOT As String
    Public Property TIRE_REAR_SMS As String
    Public Property SUSPENSION_FRONT As String
    Public Property SUSPENSION_FRONT_ANNOT As String
    Public Property SUSPENSION_FRONT_SMS As String
    Public Property SUSPENSION_REAR As String
    Public Property SUSPENSION_REAR_ANNOT As String
    Public Property SUSPENSION_REAR_SMS As String
    Public Property BRAKES_FRONT As String
    Public Property BRAKES_FRONT_ANNOT As String
    Public Property BRAKES_FRONT_SMS As String
    Public Property BRAKES_REAR As String
    Public Property BRAKES_REAR_ANNOT As String
    Public Property BRAKES_REAR_SMS As String
    Public Property EXHAUST As String
    Public Property EXHAUST_ANNOT As String
    Public Property EXHAUST_SMS As String
    Public Property DENSITY_MOTOR As String
    Public Property DENSITY_MOTOR_ANNOT As String
    Public Property DENSITY_MOTOR_SMS As String
    Public Property DENSITY_GEARBOX As String
    Public Property DENSITY_GEARBOX_ANNOT As String
    Public Property DENSITY_GEARBOX_SMS As String
    Public Property SHOCK_ABSORBER_REAR_SMS As Object
End Class
