'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmCfVatSettings
    
    '''<summary>
    '''RTlblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RTlblError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hdnPageSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnPageSize As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnSelect As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnEditCap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnEditCap As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnMode As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnSpCatgId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnSpCatgId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnSupplierId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnSupplierId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnVatCodeId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnVatCodeId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnSuppCurrNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnSuppCurrNo As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnVatPercent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnVatPercent As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lblVatSett control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVatSett As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''cbVatSettingGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbVatSettingGrid As Global.DevExpress.Web.ASPxCallbackPanel
    
    '''<summary>
    '''gvVatSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvVatSettings As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''btnEditVatSett control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditVatSett As Global.DevExpress.Web.GridViewCommandColumnCustomButton
    
    '''<summary>
    '''lblVatC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVatC As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''cbVatCodeGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbVatCodeGrid As Global.DevExpress.Web.ASPxCallbackPanel
    
    '''<summary>
    '''gvVatCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvVatCode As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''btnEditVatCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditVatCode As Global.DevExpress.Web.GridViewCommandColumnCustomButton
    
    '''<summary>
    '''H2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents H2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''spCatgGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spCatgGrid As Global.DevExpress.Web.ASPxCallbackPanel
    
    '''<summary>
    '''gvSpCatgConfig control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvSpCatgConfig As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''btnEditSpCatg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEditSpCatg As Global.DevExpress.Web.GridViewCommandColumnCustomButton
    
    '''<summary>
    '''popupSpCatg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupSpCatg As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''A3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A3 As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''lblSuppCurrNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuppCurrNo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtSupplierSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSupplierSearch As Global.System.Web.UI.HtmlControls.HtmlInputText
    
    '''<summary>
    '''lblCatg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCatg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtCatg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCatg As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''lblVC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVC As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbVatCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbVatCode As Global.DevExpress.Web.ASPxComboBox
    
    '''<summary>
    '''lblCntStock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCntStock As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''chkCntStock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCntStock As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDesc As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDesc As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''lblAccntCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccntCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtAccntCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccntCode As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''lblAllBO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAllBO As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''chkAllBO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAllBO As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblAllClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAllClass As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''chkAllClass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAllClass As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''popupVatSetting control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupVatSetting As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''a5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a5 As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''lblvatcodeprogrp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblvatcodeprogrp As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlVATCodeProdGrp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlVATCodeProdGrp As Global.DevExpress.Web.ASPxComboBox
    
    '''<summary>
    '''lblvatcodevech control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblvatcodevech As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlVATCodeVeh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlVATCodeVeh As Global.DevExpress.Web.ASPxComboBox
    
    '''<summary>
    '''lblAccCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtAccountCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccountCode As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''lblvatcustgrp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblvatcustgrp As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlVATCodeCustGrp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlVATCodeCustGrp As Global.DevExpress.Web.ASPxComboBox
    
    '''<summary>
    '''lblvatordline control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblvatordline As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlVATCodeOrdLine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlVATCodeOrdLine As Global.DevExpress.Web.ASPxComboBox
    
    '''<summary>
    '''popupVatCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupVatCode As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''a7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a7 As Global.System.Web.UI.HtmlControls.HtmlAnchor
    
    '''<summary>
    '''lblVATCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVATCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtVATCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVATCode As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''lblVatPercentage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVatPercentage As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtVatPercentage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVatPercentage As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''lblExtVATCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtVATCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtExtVAT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExtVAT As Global.DevExpress.Web.ASPxTextBox
    
    '''<summary>
    '''lblExtAccCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtAccCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtExtAcc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExtAcc As Global.DevExpress.Web.ASPxTextBox
End Class
