'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmConfigGeneral
    
    '''<summary>
    '''lblHead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHead As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''RTlblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RTlblError As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''hdnPageSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnPageSize As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnEditCap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnEditCap As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnMode As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnSelect As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnZipCodeId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnZipCodeId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnDiscCodeId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnDiscCodeId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnVATCodeId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnVATCodeId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnReasonId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnReasonId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnStationTypeId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnStationTypeId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnDeptMessId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnDeptMessId As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''lblGenSett control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGenSett As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblTimeFormat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTimeFormat As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbTimeFormat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbTimeFormat As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblUnitofTimings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUnitofTimings As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cmbUnitofTimings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbUnitofTimings As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrency As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCurrency As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblMinimumSplits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMinimumSplits As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtMinimumSplits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMinimumSplits As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblSubRepairCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubRepairCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbSubRepairCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbSubRepairCode As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lbldayPlanCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldayPlanCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbSubDayPlan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbSubDayPlan As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblUseDynCT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUseDynCT As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbUseDynCT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbUseDynCT As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblJobCard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJobCard As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbJobCard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbJobCard As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblEditStdTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEditStdTime As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbEditStdTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbEditStdTime As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblViewGarSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblViewGarSummary As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbViewGarSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbViewGarSummary As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblMonday control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMonday As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbMonday control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbMonday As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblVhReg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVhReg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbVhReg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbVhReg As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblUseInvPdf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUseInvPdf As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbUseInvPdf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbUseInvPdf As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblUseDBSLnk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUseDBSLnk As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbUseDBSLnk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbUseDBSLnk As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblUseApprove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUseApprove As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbUseApprove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbUseApprove As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblUseMechGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUseMechGrid As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbUseMechGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbUseMechGrid As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblSortByLoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSortByLoc As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbSortbyLoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbSortbyLoc As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblStdTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStdTime As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbStdTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbStdTime As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblChgTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblChgTime As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbChgTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbChgTime As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblMileage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMileage As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbMileage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbMileage As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblSaveUdDp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaveUdDp As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbSaveUdDp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbSaveUdDp As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDispIntNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDispIntNote As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbDispIntNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDispIntNote As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblSpBO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSpBO As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbSpBO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbSpBO As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDispWOSpares control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDispWOSpares As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbWOSpares control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbWOSpares As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblZipCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblZipCode As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''cbZipCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbZipCode As Global.DevExpress.Web.ASPxCallbackPanel
    
    '''<summary>
    '''gvZipCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvZipCode As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''lblDiscCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDiscCode As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''cbDiscCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDiscCode As Global.DevExpress.Web.ASPxCallbackPanel
    
    '''<summary>
    '''gvDiscCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvDiscCode As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''H1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents H1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''cbReasonFrLv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbReasonFrLv As Global.DevExpress.Web.ASPxCallbackPanel
    
    '''<summary>
    '''gvReasonFrLv control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvReasonFrLv As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''lblStationType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStationType As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''cbStationType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbStationType As Global.DevExpress.Web.ASPxCallbackPanel
    
    '''<summary>
    '''gvStationType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvStationType As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''lblSMSSettings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSMSSettings As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblSMSMailServer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSMSMailServer As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtSMSMailServer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSMSMailServer As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblSMSPrefix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSMSPrefix As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtSMSPrefix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSMSPrefix As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblSMSSuffix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSMSSuffix As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtSMSSuffix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSMSSuffix As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblSMSCtryCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSMSCtryCode As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtSMSCtryCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSMSCtryCode As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblSMSNoChars control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSMSNoChars As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtSMSNoChars control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSMSNoChars As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblSMSStartDigits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSMSStartDigits As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtSMSStartDigits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSMSStartDigits As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblSMSUseEMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSMSUseEMail As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''cbSMSUseEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbSMSUseEmail As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''lblDeptMess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDeptMess As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''cbDeptMess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDeptMess As Global.DevExpress.Web.ASPxCallbackPanel
    
    '''<summary>
    '''gvDeptMess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvDeptMess As Global.DevExpress.Web.ASPxGridView
End Class
