'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmCfWorkOrder

    '''<summary>
    '''lblHead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHead As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RTlblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RTlblError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hdnPageSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnPageSize As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnEditCap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnEditCap As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnMode As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnSelect As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnPayTypeId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnPayTypeId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnVATCodeId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnVATCodeId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''a2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a2 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lblSubsidiary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubsidiary As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlSubsidiary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSubsidiary As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblDepartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDepartment As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlDepartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDepartment As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblOrderNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrderNumber As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOrderNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOrderNumber As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblIsVatCalculate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblIsVatCalculate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkIsVatCalculate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkIsVatCalculate As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblOrderSeries control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrderSeries As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtOrderSeries control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOrderSeries As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblChargeBasedOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblChargeBasedOn As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbChargeBasedOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbChargeBasedOn As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblGarageMaterial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGarageMaterial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtGarageMaterialPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGarageMaterialPrice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPerLabPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPerLabPrice As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUseDeliveryAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUseDeliveryAddress As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkUseDeliveryAddress control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkUseDeliveryAddress As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblUseManualRwrk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUseManualRwrk As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkUseManualRwrk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkUseManualRwrk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblUseVehicle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUseVehicle As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkUseVehicle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkUseVehicle As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblUsePCJob control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUsePCJob As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkUsePCJob control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkUsePCJob As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblDefStat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDefStat As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkDefStat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDefStat As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''ddlStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblCnfrnDialog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCnfrnDialog As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkCnfrmDialog control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCnfrmDialog As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblSaveJob control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaveJob As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkSaveJob control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSaveJob As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblCurWRSeries control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurWRSeries As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RTlblOrderNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RTlblOrderNumber As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCurOrdSeries control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurOrdSeries As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RTlblOrderSeries control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RTlblOrderSeries As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCurrGMPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrGMPrice As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RTlblGarageMaterial control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RTlblGarageMaterial As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCurSer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurSer As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RTlblCurSeries control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RTlblCurSeries As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblUseDefCust control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUseDefCust As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkUseDefCust control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkUseDefCust As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblCustID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomer As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblUseVAACCCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUseVAACCCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkVAACCCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkVAACCCode As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblVAcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVAcode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtVACode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVACode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblUseAllSpareSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUseAllSpareSearch As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkAllSpareSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAllSpareSearch As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblDispRINVPINV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDispRINVPINV As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkDispRINVPINV control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkDispRINVPINV As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnSaveWOC control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveWOC As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''a1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a1 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''btnAddPayTypeT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddPayTypeT As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnDelPayTypeT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelPayTypeT As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnAddPayTypeB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddPayTypeB As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnDelPayTypeB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelPayTypeB As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''a3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a3 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lblPayType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPayType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPayType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPayType As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblPayTypeDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPayTypeDesc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPayTypeDesc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPayTypeDesc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSavePayType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSavePayType As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnResetPayType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnResetPayType As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''a4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a4 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''btnAddVATCodeT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddVATCodeT As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnDelVATCodeT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelVATCodeT As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnAddVATCodeB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddVATCodeB As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnDelVATCodeB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelVATCodeB As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''a5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a5 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lblvatcodeprogrp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblvatcodeprogrp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlVATCodeProdGrp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlVATCodeProdGrp As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblvatcustgrp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblvatcustgrp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlVATCodeCustGrp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlVATCodeCustGrp As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblvatcodevech control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblvatcodevech As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlVATCodeVeh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlVATCodeVeh As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblvatordline control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblvatordline As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlVATCodeOrdLine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlVATCodeOrdLine As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblAccCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAccCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtAccountCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccountCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSaveVATCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveVATCode As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnResetVATCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnResetVATCode As Global.System.Web.UI.HtmlControls.HtmlInputButton
End Class
