'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmCfGeneral

    '''<summary>
    '''lblHead control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHead As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RTlblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RTlblError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hdnPageSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnPageSize As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnEditCap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnEditCap As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnMode As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnSelect As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnZipCodeId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnZipCodeId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnDiscCodeId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnDiscCodeId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnVATCodeId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnVATCodeId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnReasonId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnReasonId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnStationTypeId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnStationTypeId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnDeptMessId control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnDeptMessId As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''a2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a2 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lblTimeFormat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTimeFormat As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbTimeFormat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbTimeFormat As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblUnitofTimings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUnitofTimings As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cmbUnitofTimings control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbUnitofTimings As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCurrency As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCurrency As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblMinimumSplits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMinimumSplits As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMinimumSplits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMinimumSplits As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSubRepairCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSubRepairCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbSubRepairCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbSubRepairCode As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lbldayPlanCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldayPlanCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbSubDayPlan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbSubDayPlan As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblUseDynCT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUseDynCT As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbUseDynCT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbUseDynCT As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblJobCard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJobCard As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbJobCard control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbJobCard As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblEditStdTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEditStdTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbEditStdTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbEditStdTime As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblViewGarSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblViewGarSummary As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbViewGarSummary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbViewGarSummary As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblMonday control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMonday As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbMonday control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbMonday As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblVhReg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVhReg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbVhReg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbVhReg As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblUseInvPdf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUseInvPdf As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbUseInvPdf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbUseInvPdf As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblUseDBSLnk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUseDBSLnk As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbUseDBSLnk control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbUseDBSLnk As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblUseApprove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUseApprove As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbUseApprove control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbUseApprove As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblUseMechGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUseMechGrid As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbUseMechGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbUseMechGrid As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblSortByLoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSortByLoc As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbSortbyLoc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbSortbyLoc As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblStdTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStdTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbStdTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbStdTime As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblChgTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblChgTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbChgTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbChgTime As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblMileage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMileage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbMileage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbMileage As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblSaveUdDp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSaveUdDp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbSaveUdDp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbSaveUdDp As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblDispIntNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDispIntNote As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbDispIntNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDispIntNote As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblSpBO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSpBO As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbSpBO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbSpBO As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblDispWOSpares control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDispWOSpares As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbWOSpares control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbWOSpares As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnSaveGenSett control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveGenSett As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''a1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a1 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''btnAddZipCodeT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddZipCodeT As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnDelZipCodeT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelZipCodeT As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnAddZipCodeB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddZipCodeB As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnDelZipCodeB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelZipCodeB As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''a3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a3 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lblZipCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblZipCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtZipCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtZipCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCountry As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCountry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCountry As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblState As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtState control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtState As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCity As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCity control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCity As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSaveZipCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveZipCode As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnResetZipCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnResetZipCode As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''a4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a4 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''btnAddDiscCodeT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddDiscCodeT As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnDelDiscCodeT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelDiscCodeT As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnAddDiscCodeB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddDiscCodeB As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnDelDiscCodeB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelDiscCodeB As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''a5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a5 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lblDiscCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDiscCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDiscCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDiscCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSaveDiscCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveDiscCode As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnResetDiscCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnResetDiscCode As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''a6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a6 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''btnAddVATCodeT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddVATCodeT As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnDelVATCodeT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelVATCodeT As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnAddVATCodeB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddVATCodeB As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnDelVATCodeB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelVATCodeB As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''a7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a7 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lblVATCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVATCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtVATCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVATCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblVatPercentage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVatPercentage As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtVatPercentage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVatPercentage As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblExtVATCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtVATCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtExtVAT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExtVAT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblExtAccCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExtAccCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtExtAcc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExtAcc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSaveVATCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveVATCode As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnResetVATCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnResetVATCode As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''a8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a8 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''btnAddReasonT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddReasonT As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnDelReasonT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelReasonT As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnAddReasonB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddReasonB As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnDelReasonB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelReasonB As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''a9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a9 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lblReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblReason As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtReason As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSaveReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveReason As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnResetReason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnResetReason As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''a10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a10 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''btnAddStationTypeT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddStationTypeT As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnDelStationTypeT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelStationTypeT As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnAddStationTypeB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddStationTypeB As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnDelStationTypeB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelStationTypeB As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''a11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a11 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lblStationType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStationType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtStationType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStationType As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSaveStationType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveStationType As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnResetStationType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnResetStationType As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''a12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a12 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''a13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a13 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lblSMSMailServer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSMSMailServer As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSMSMailServer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSMSMailServer As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSMSPrefix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSMSPrefix As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSMSPrefix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSMSPrefix As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSMSSuffix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSMSSuffix As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSMSSuffix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSMSSuffix As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSMSCtryCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSMSCtryCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSMSCtryCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSMSCtryCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSMSNoChars control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSMSNoChars As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSMSNoChars control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSMSNoChars As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSMSStartDigits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSMSStartDigits As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSMSStartDigits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSMSStartDigits As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSMSUseEMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSMSUseEMail As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbSMSUseEmail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbSMSUseEmail As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnSaveSMS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveSMS As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''a14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a14 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''btnAddDeptMessT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddDeptMessT As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnDelDeptMessT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelDeptMessT As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnAddDeptMessB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddDeptMessB As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnDelDeptMessB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDelDeptMessB As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''a15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents a15 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lblDept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDept As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlDept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDept As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblEditCommercialText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEditCommercialText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEditCommercialText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditCommercialText As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblEditDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEditDetails As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEditDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEditDetails As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSaveDeptMess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveDeptMess As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''btnResetDeptMess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnResetDeptMess As Global.System.Web.UI.HtmlControls.HtmlInputButton
End Class
