'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmCfLA

    '''<summary>
    '''lblHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHeader As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''RTlblError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RTlblError As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''hdnPageSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnPageSize As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnSelect As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnEditCap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnEditCap As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnMode As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''header control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents header As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''A1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A1 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''rdbGrouping control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdbGrouping As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''A2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A2 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''rdbExportMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdbExportMode As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''A3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A3 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''rdbInvExp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdbInvExp As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''A4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A4 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lblInvoiceJournal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInvoiceJournal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtInvoiceJournal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInvoiceJournal As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblInvJournalCustInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInvJournalCustInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtInvJournalCustInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInvJournalCustInfo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''A5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A5 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lblCustomerInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomerInfo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCustomerInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomerInfo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCustomerBalance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomerBalance As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtCustomerBalance control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomerBalance As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''A6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A6 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lblPrefix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrefix As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPrefix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPrefix As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSuffix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuffix As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlSuffix control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSuffix As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblSeqNos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSeqNos As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbSeqNos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbSeqNos As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblTransactionNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTransactionNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtTransactionNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTransactionNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblExpTypeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExpTypeName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlExpTypeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlExpTypeName As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblUseInvNoForSort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUseInvNoForSort As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbUseInvNoForSort control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbUseInvNoForSort As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblUseCreditNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUseCreditNote As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbUseCreditNote control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbUseCreditNote As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblUseBlankSp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUseBlankSp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbUseBlankSp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbUseBlankSp As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblCombinelines control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCombinelines As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbCombinelines control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbCombinelines As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblSplitSubsidiary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSplitSubsidiary As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbSplitSubsidiary control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbSplitSubsidiary As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblRemCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRemCost As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbRemCost control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbRemCost As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblDispalyVchrType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDispalyVchrType As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbDisplayVchrType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDisplayVchrType As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''drpDisplayVchrType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpDisplayVchrType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblDisplayInvNumbers control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDisplayInvNumbers As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbDisplayInvNum control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbDisplayInvNum As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblAddDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddDate As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbAddDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbAddDate As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblAddText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAddText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbAddText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbAddText As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtAddText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAddText As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblAdditionalText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAdditionalText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbAdditionalText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbAdditionalText As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtAdditionalText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAdditionalText As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCustomerText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustomerText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbCustomerText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbCustomerText As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txtCustomerText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCustomerText As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblErrorAccountCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorAccountCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtErrAccCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtErrAccCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblFixedPriceAccCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFixedPriceAccCode As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtFPAccCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFPAccCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblExportValidation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblExportValidation As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbExpValid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbExpValid As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblErrInvName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrInvName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtErrInvName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtErrInvName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''A7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A7 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lblPrefix2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPrefix2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPrefix_ExpCustInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPrefix_ExpCustInfo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblSuffix2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSuffix2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlSuffixCustInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSuffixCustInfo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblCustSeqNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustSeqNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbCustseqNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbCustseqNo As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblSeqNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSeqNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSeqNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSeqNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblCustExpTypeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustExpTypeName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlCustTemplate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCustTemplate As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lbluseBillAddrExp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbluseBillAddrExp As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''cbUseBillAddr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbUseBillAddr As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''A8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A8 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''rbtnDaily control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtnDaily As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''lblEvery control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEvery As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDailyEvery control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDailyEvery As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''drpdailyHM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents drpdailyHM As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblStartTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStartTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDailyStTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDailyStTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblEndTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEndTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtDailyEndTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDailyEndTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rbtnWeekly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtnWeekly As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''lblEvery2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEvery2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlWeeklyEvery control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlWeeklyEvery As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTime As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtWeeklyTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtWeeklyTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rbtnMonthly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbtnMonthly As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''lblEvery3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEvery3 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlMonthly control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMonthly As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblTime2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTime2 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMonthlyTime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMonthlyTime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''A9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents A9 As Global.System.Web.UI.HtmlControls.HtmlAnchor

    '''<summary>
    '''lblOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrder As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDetails As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblLength control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblLength As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlCustID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCustID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblCustID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlOrderNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOrderNo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblOrderNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrderNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlRegNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRegNo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblRegNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRegNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlVinNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlVinNo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblVinNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblVinNo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtVinNumLen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVinNumLen As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlCustName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCustName As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblCustName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCustName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblFixedText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblFixedText As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtFixText control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFixText As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.HtmlControls.HtmlInputButton
End Class
