'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmDayPlan
    
    '''<summary>
    '''hdCopiedAppointmentID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdCopiedAppointmentID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdType As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnIsOpnAptExtClicked control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnIsOpnAptExtClicked As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''resourcePopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents resourcePopup As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''LastSelectedNodeKey control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents LastSelectedNodeKey As Global.DevExpress.Web.ASPxHiddenField
    
    '''<summary>
    '''resourceGroupList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents resourceGroupList As Global.DevExpress.Web.ASPxTreeList.ASPxTreeList
    
    '''<summary>
    '''customViewNav control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents customViewNav As Global.DevExpress.Web.ASPxScheduler.ASPxViewNavigator
    
    '''<summary>
    '''lblDayOfWeek control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDayOfWeek As Global.DevExpress.Web.ASPxLabel
    
    '''<summary>
    '''customVisibleInterval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents customVisibleInterval As Global.DevExpress.Web.ASPxScheduler.ASPxViewVisibleInterval
    
    '''<summary>
    '''cbJobStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbJobStatus As Global.DevExpress.Web.ASPxCallback
    
    '''<summary>
    '''schdMechanics control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents schdMechanics As Global.DevExpress.Web.ASPxScheduler.ASPxScheduler
    
    '''<summary>
    '''hdnRefreshSch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnRefreshSch As Global.DevExpress.Web.ASPxHiddenField
    
    '''<summary>
    '''hdnRefreshOnHold control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnRefreshOnHold As Global.DevExpress.Web.ASPxHiddenField
    
    '''<summary>
    '''hdnAddNewRow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnAddNewRow As Global.DevExpress.Web.ASPxHiddenField
    
    '''<summary>
    '''ASPxPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ASPxPanel1 As Global.DevExpress.Web.ASPxPanel
    
    '''<summary>
    '''gvOnHold control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvOnHold As Global.DevExpress.Web.ASPxGridView
    
    '''<summary>
    '''ge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ge As Global.DevExpress.Web.ASPxGlobalEvents
    
    '''<summary>
    '''resourceDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents resourceDataSource As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''appointmentDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents appointmentDataSource As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''resourceTreeListDataSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents resourceTreeListDataSource As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''existOrdersPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents existOrdersPopup As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''lblHeader control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblHeader As Global.DevExpress.Web.ASPxLabel
    
    '''<summary>
    '''cbOrderList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbOrderList As Global.DevExpress.Web.ASPxCallbackPanel
    
    '''<summary>
    '''lbExisOrders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbExisOrders As Global.DevExpress.Web.ASPxListBox
    
    '''<summary>
    '''popupOnHoldApp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents popupOnHoldApp As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''cbOnHoldList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbOnHoldList As Global.DevExpress.Web.ASPxCallbackPanel
    
    '''<summary>
    '''lbOnHoldApp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbOnHoldApp As Global.DevExpress.Web.ASPxListBox
    
    '''<summary>
    '''ordersPopup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ordersPopup As Global.DevExpress.Web.ASPxPopupControl
    
    '''<summary>
    '''lbChooseAction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbChooseAction As Global.DevExpress.Web.ASPxLabel
    
    '''<summary>
    '''rbListOrdersMenu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbListOrdersMenu As Global.DevExpress.Web.ASPxRadioButtonList
    
    '''<summary>
    '''cbOrders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbOrders As Global.DevExpress.Web.ASPxCallbackPanel
    
    '''<summary>
    '''lblOrderList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOrderList As Global.DevExpress.Web.ASPxLabel
    
    '''<summary>
    '''lbOrdersList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbOrdersList As Global.DevExpress.Web.ASPxListBox
    
    '''<summary>
    '''lblAllApp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAllApp As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblAptSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAptSearch As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblSelDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelDate As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dateSelector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dateSelector As Global.DevExpress.Web.ASPxDateEdit
    
    '''<summary>
    '''chkhistoryApt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkhistoryApt As Global.System.Web.UI.HtmlControls.HtmlInputCheckBox
    
    '''<summary>
    '''btnSearchApt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearchApt As Global.System.Web.UI.HtmlControls.HtmlInputButton
    
    '''<summary>
    '''cbAllAptGrid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbAllAptGrid As Global.DevExpress.Web.ASPxCallbackPanel
    
    '''<summary>
    '''gvAllAppointments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvAllAppointments As Global.DevExpress.Web.ASPxGridView
End Class
